#!/usr/bin/env bash
#
# install-clamd-remote.sh (multi-distro)
#
# Auto-detects the Linux distribution and its package manager, installs clamd
# (the ClamAV daemon) and configures it to accept remote TCP connections,
# working around the known systemd socket-activation issue on some distros
# (Debian/Ubuntu "bookworm"+, Arch) where TCPSocket/TCPAddr in the config file
# are ignored because a clamav-daemon.socket / clamd.socket is present.
#
#
# Supported distros (auto-detected):
#   - Debian / Ubuntu / Raspberry Pi OS  -> apt
#   - RHEL / CentOS / Rocky / AlmaLinux / Fedora -> dnf (fallback yum)
#   - Arch Linux / Manjaro               -> pacman
#   - openSUSE                            -> zypper
#   - Alpine Linux                        -> apk (OpenRC init, not systemd)
#
# USAGE:
#   sudo ./install-clamd-remote.sh [options]
#
# OPTIONS:
#   --port PORT           clamd TCP port (default: 3310)
#   --bind ADDRESS        Address clamd listens on (default: 0.0.0.0)
#   --console-ip IP       IP of the web console: when given, the firewall (ufw or
#                          firewalld, if present) is opened ONLY for that IP.
#   --skip-install        Do not install packages (reconfigure only)
#   --scan-system         Configure clamd to scan the WHOLE machine
#                          (User root + SELinux boolean antivirus_can_scan_system).
#                          WARNING: clamd will read any file as root; always use
#                          --console-ip to restrict access to the port.
#
#   REALTIME PROTECTION (on-access) + automatic reporting to the console:
#   --on-access           Enable the on-access scanner (clamonacc): files are
#                          checked as they are written/opened, and every detection
#                          is sent to the web console IMMEDIATELY
#                          (POST /api/scan/report), which sends the Telegram alert.
#                          Requires --console-url plus --console-key (or user/pass).
#                          Traffic is OUTBOUND only: no port to open.
#   --console-url URL     Console URL (e.g. https://console.example.com)
#   --console-key KEY     Endpoint key generated by the console (recommended: it is
#                          valid for this endpoint only). Alternatively use
#                          --console-user/--console-pass with an OPERATOR user.
#   --console-user USER   Dedicated OPERATOR user created in /admin/users
#   --console-pass PWD    That user's password
#   --watch-path PATH     Directory to watch in realtime (repeatable).
#                          Default: /home /root /srv /opt /var/www /tmp
#                          It CANNOT be "/" (fanotify would loop).
#   --agent-mode          Called by the agent installer: suppresses the closing
#                          "add this endpoint" / firewall notes, which do not
#                          apply when the machine calls the console itself.
#   --on-access-prevent   Besides reporting, BLOCK access to infected files.
#                          Powerful but intrusive: a false positive can break
#                          running applications. Default: report only.
#
#   -h, --help             Show this help
#
# EXAMPLES:
#   sudo ./install-clamd-remote.sh --console-ip 192.168.1.50
#   sudo ./install-clamd-remote.sh --scan-system --console-ip 192.168.1.50
#   sudo ./install-clamd-remote.sh --scan-system --console-ip 192.168.1.50 \
#        --on-access --console-url http://192.168.1.50:8080 \
#        --console-key 'cav_...'
#
# NOTE: --on-access requires clamav-onacc-report.sh to sit next to this script
#       (copy both onto the machine).
#
set -euo pipefail

PORT=3310
BIND_ADDR="0.0.0.0"
CONSOLE_IP=""
SKIP_INSTALL=0
SCAN_SYSTEM=0
ON_ACCESS=0
ON_ACCESS_PREVENT=0
# Set by the agent installer: it prints its own summary, so the endpoint/firewall
# advice below would only contradict it (with an agent nothing listens inbound).
AGENT_MODE=0
CONSOLE_URL=""
CONSOLE_KEY=""
CONSOLE_USER=""
CONSOLE_PASS=""
WATCH_PATHS=()

log()  { echo -e "\033[1;34m[*]\033[0m $*"; }
ok()   { echo -e "\033[1;32m[OK]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }
err()  { echo -e "\033[1;31m[ERROR]\033[0m $*" >&2; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port) PORT="$2"; shift 2 ;;
    --bind) BIND_ADDR="$2"; shift 2 ;;
    --console-ip) CONSOLE_IP="$2"; shift 2 ;;
    --skip-install) SKIP_INSTALL=1; shift ;;
    --scan-system) SCAN_SYSTEM=1; shift ;;
    --on-access) ON_ACCESS=1; shift ;;
    --agent-mode) AGENT_MODE=1; shift ;;
    --on-access-prevent) ON_ACCESS_PREVENT=1; shift ;;
    --console-url) CONSOLE_URL="$2"; shift 2 ;;
    --console-key) CONSOLE_KEY="$2"; shift 2 ;;
    --console-user) CONSOLE_USER="$2"; shift 2 ;;
    --console-pass) CONSOLE_PASS="$2"; shift 2 ;;
    --watch-path) WATCH_PATHS+=("$2"); shift 2 ;;
    -h|--help) awk 'NR==1{next} /^#/{sub(/^# ?/,""); print; next} {exit}' "$0"; exit 0 ;;
    *) err "Unknown option: $1"; exit 1 ;;
  esac
done

if [[ $EUID -ne 0 ]]; then
  err "This script must be run with sudo/root."
  exit 1
fi

# Path of the script that forwards on-access detections to the console.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORT_SCRIPT_SRC="${SCRIPT_DIR}/clamav-onacc-report.sh"

if [[ $ON_ACCESS -eq 1 ]]; then
  if [[ -z "$CONSOLE_URL" ]]; then
    err "--on-access richiede --console-url."
    exit 1
  fi
  if [[ -z "$CONSOLE_KEY" && ( -z "$CONSOLE_USER" || -z "$CONSOLE_PASS" ) ]]; then
    err "--on-access requires --console-key (recommended) or --console-user + --console-pass."
    err "Generate the key in the console: Admin > Endpoints > Agent > Generate key."
    exit 1
  fi
  if [[ ! -f "$REPORT_SCRIPT_SRC" ]]; then
    err "Cannot find $REPORT_SCRIPT_SRC."
    err "--on-access needs clamav-onacc-report.sh next to this script:"
    err "  scp install-clamd-remote.sh clamav-onacc-report.sh user@machine:~/"
    exit 1
  fi
  if [[ ${#WATCH_PATHS[@]} -eq 0 ]]; then
    WATCH_PATHS=(/home /root /srv /opt /var/www /tmp)
  fi
  for _p in "${WATCH_PATHS[@]}"; do
    if [[ "$_p" == "/" ]]; then
      err "--watch-path / is not supported: watching the root sends fanotify into a loop"
      err "and hangs the machine. Point it at directories holding data (e.g. /home /srv)."
      exit 1
    fi
    if [[ "$_p" != /* ]]; then
      err "--watch-path must be an absolute path: '$_p'"
      exit 1
    fi
  done
fi

# ---------------------------------------------------------------------------
# 1) Rilevamento distro / package manager
# ---------------------------------------------------------------------------
PKG_MGR=""
if command -v apt-get >/dev/null 2>&1; then PKG_MGR="apt"
elif command -v dnf >/dev/null 2>&1; then PKG_MGR="dnf"
elif command -v yum >/dev/null 2>&1; then PKG_MGR="yum"
elif command -v pacman >/dev/null 2>&1; then PKG_MGR="pacman"
elif command -v zypper >/dev/null 2>&1; then PKG_MGR="zypper"
elif command -v apk >/dev/null 2>&1; then PKG_MGR="apk"
else
  err "No supported package manager found (apt/dnf/yum/pacman/zypper/apk)."
  exit 1
fi

DISTRO_ID="unknown"
[[ -f /etc/os-release ]] && DISTRO_ID=$(. /etc/os-release && echo "${PRETTY_NAME:-$ID}")
log "Detected distro: $DISTRO_ID  ->  package manager: $PKG_MGR"

# Rilevamento init system (systemd vs OpenRC, es. Alpine)
INIT_SYS="systemd"
if [[ "$PKG_MGR" == "apk" ]] || ! command -v systemctl >/dev/null 2>&1; then
  INIT_SYS="openrc"
fi
log "Init system: $INIT_SYS"

# ---------------------------------------------------------------------------
# 2) Package installation (per distro)
# ---------------------------------------------------------------------------
if [[ $SKIP_INSTALL -eq 0 ]]; then
  log "Installing clamd for this distro..."
  case "$PKG_MGR" in
    apt)
      apt-get update -qq
      DEBIAN_FRONTEND=noninteractive apt-get install -y -qq clamav-daemon clamav-freshclam
      ;;
    dnf|yum)
      if grep -qiE '^ID=(rhel|centos|rocky|almalinux)' /etc/os-release 2>/dev/null; then
        log "RHEL-like distro: trying to enable EPEL (if not already present)..."
        "$PKG_MGR" install -y epel-release 2>/dev/null || warn "epel-release was not installed automatically: if the clamav install fails, enable EPEL manually."
      fi
      "$PKG_MGR" install -y clamav clamav-update clamd 2>/dev/null || \
        "$PKG_MGR" install -y clamav clamd 2>/dev/null || \
        "$PKG_MGR" install -y clamav
      ;;
    pacman)
      pacman -Sy --noconfirm --needed clamav
      ;;
    zypper)
      zypper --non-interactive install clamav
      ;;
    apk)
      apk update
      apk add clamav clamav-daemon
      ;;
  esac
  ok "Pacchetti installati."
else
  log "Salto installazione pacchetti (--skip-install)."
fi

# ---------------------------------------------------------------------------
# 3) Locate the clamd.conf configuration file
# ---------------------------------------------------------------------------
CLAMD_CONF=""
for candidate in /etc/clamav/clamd.conf /etc/clamd.d/scan.conf /etc/clamd.conf; do
  if [[ -f "$candidate" ]]; then
    CLAMD_CONF="$candidate"
    break
  fi
done

if [[ -z "$CLAMD_CONF" ]]; then
  err "No clamd configuration file found (checked: /etc/clamav/clamd.conf, /etc/clamd.d/scan.conf, /etc/clamd.conf)."
  err "The package install may not have created a default config: check manually."
  exit 1
fi
log "Configuration file: $CLAMD_CONF"

# ---------------------------------------------------------------------------
# 4) Update the signature database (freshclam)
# ---------------------------------------------------------------------------
log "Updating the signature database (freshclam)..."
if [[ "$INIT_SYS" == "systemd" ]]; then
  systemctl stop clamav-freshclam 2>/dev/null || true
fi
freshclam --stdout || warn "freshclam reported a warning (often normal on a first run, e.g. database already up to date). Continuing."

# On some distros clamd (via systemd socket activation) only starts if the
# signature database is already on disk (ConditionPathExistsGlob). If freshclam
# has not finished downloading it yet we wait here, otherwise the socket unit is
# skipped and clamd may end up binding the port on its own, which then conflicts
# when the socket unit retries later.
log "Checking that the signature database is on disk..."
db_present() {
  [[ -f /var/lib/clamav/daily.cvd || -f /var/lib/clamav/daily.cld ]] || \
  [[ -f /var/lib/clamav/main.cvd  || -f /var/lib/clamav/main.cld  ]]
}
DB_WAIT=0
while ! db_present; do
  if [[ $DB_WAIT -ge 120 ]]; then
    warn "The signature database is still not present after 2 minutes of waiting."
    warn "Running freshclam once more to surface the error:"
    freshclam --stdout || true
    break
  fi
  sleep 5
  DB_WAIT=$((DB_WAIT + 5))
  log "  ...still waiting for the signature database (${DB_WAIT}s)"
done
ok "Signature database ready (or proceeding anyway after the maximum wait)."

# ---------------------------------------------------------------------------
# 5) Determine the systemd unit name(s) for clamd (they vary per distro)
# ---------------------------------------------------------------------------
CLAMD_SERVICE=""
CLAMD_SOCKET=""
FRESHCLAM_SERVICE=""

# Robust unit-existence check, independent of the tabular format of
# "systemctl list-unit-files" (which varies across versions/distros).
unit_exists() {
  local state
  state=$(systemctl show -p LoadState --value "$1" 2>/dev/null || echo "not-found")
  [[ "$state" == "loaded" || "$state" == "masked" ]]
}

# Checks whether a TEMPLATE unit exists (e.g. clamd@.service).
# For a bare template (no instance) systemctl show reports LoadState=stub, so
# unit_exists() would consider it absent: we use "systemctl cat", which instead
# returns the template content when it exists.
template_exists() {
  systemctl cat "$1" >/dev/null 2>&1
}

if [[ "$INIT_SYS" == "systemd" ]]; then
  # RHEL/Fedora distros use a TEMPLATE unit clamd@.service, instantiated with the
  # name of the config file: /etc/clamd.d/scan.conf -> clamd@scan.
  # We derive the instance name from the config already detected (nothing hardcoded).
  CLAMD_INSTANCE=""
  case "$CLAMD_CONF" in
    /etc/clamd.d/*.conf) CLAMD_INSTANCE="$(basename "$CLAMD_CONF" .conf)" ;;
  esac

  systemctl stop clamav-daemon.service clamav-daemon.socket 2>/dev/null || true
  [[ -n "$CLAMD_INSTANCE" ]] && systemctl stop "clamd@${CLAMD_INSTANCE}.service" 2>/dev/null || true
  systemctl stop clamd.service 2>/dev/null || true

  if unit_exists clamav-daemon.service; then
    CLAMD_SERVICE="clamav-daemon.service"
    unit_exists clamav-daemon.socket && CLAMD_SOCKET="clamav-daemon.socket"
  elif [[ -n "$CLAMD_INSTANCE" ]] && template_exists 'clamd@.service'; then
    CLAMD_SERVICE="clamd@${CLAMD_INSTANCE}.service"
  elif unit_exists clamd.service; then
    CLAMD_SERVICE="clamd.service"
  fi

  unit_exists clamav-freshclam.service && FRESHCLAM_SERVICE="clamav-freshclam.service"

  if [[ -z "$CLAMD_SERVICE" ]]; then
    err "Cannot determine the systemd unit name for clamd on this distro automatically."
    err "Available units containing 'clam':"
    systemctl list-unit-files 2>/dev/null | grep -i clam || true
    err "Send me this list so we can update the script for your distro."
    exit 1
  fi
  log "Unita' clamd: $CLAMD_SERVICE${CLAMD_SOCKET:+ (socket: $CLAMD_SOCKET)}"
fi

# ---------------------------------------------------------------------------
# 6) Configure clamd.conf: TCPSocket + TCPAddr (idempotent)
# ---------------------------------------------------------------------------
log "Configuring $CLAMD_CONF to listen on TCP..."
cp "$CLAMD_CONF" "${CLAMD_CONF}.bak.$(date +%Y%m%d%H%M%S)"

set_conf_value() {
  local key="$1" value="$2" file="$3"
  if grep -qE "^[#[:space:]]*${key}[[:space:]]" "$file"; then
    sed -i -E "s|^[#[:space:]]*${key}[[:space:]].*|${key} ${value}|" "$file"
  else
    echo "${key} ${value}" >> "$file"
  fi
}

# Some keys (OnAccessIncludePath/OnAccessExcludePath) may appear more than once:
# here we delete every existing occurrence and rewrite the list, so re-running
# the script does not accumulate duplicates.
set_conf_multi() {
  local key="$1"; shift
  local file="$1"; shift
  sed -i -E "/^[#[:space:]]*${key}[[:space:]]/d" "$file"
  local v
  for v in "$@"; do
    echo "${key} ${v}" >> "$file"
  done
}

# Fedora/RHEL: the default config (/etc/clamd.d/scan.conf) contains an "Example"
# line that makes clamd refuse to start ("Please edit the example config file")
# until it is removed/commented out. Idempotent: it only acts when a standalone
# "Example" line exists.
if grep -qE '^[[:space:]]*Example[[:space:]]*$' "$CLAMD_CONF"; then
  sed -i -E 's|^[[:space:]]*Example[[:space:]]*$|# Example (commentata da install-clamd-remote.sh)|' "$CLAMD_CONF"
  ok "'Example' line commented out in $CLAMD_CONF (required on Fedora/RHEL for clamd to start)."
fi

set_conf_value "TCPSocket" "$PORT" "$CLAMD_CONF"
set_conf_value "TCPAddr" "$BIND_ADDR" "$CLAMD_CONF"
ok "TCPSocket = $PORT, TCPAddr = $BIND_ADDR set (a backup was saved next to the original)."

# --scan-system: enables scanning the WHOLE filesystem through PATH scans.
# Over TCP fd-pass is unavailable, so clamd itself opens the files: to read any
# path it must run as root AND, on SELinux systems, have the
# antivirus_can_scan_system boolean enabled. Without both, paths outside clamd's
# own contexts fail with "Permission denied".
if [[ "$SCAN_SYSTEM" -eq 1 ]]; then
  log "--scan-system mode: configuring clamd to read the whole filesystem..."
  set_conf_value "User" "root" "$CLAMD_CONF"
  if command -v getenforce >/dev/null 2>&1 && [[ "$(getenforce 2>/dev/null)" != "Disabled" ]]; then
    if command -v setsebool >/dev/null 2>&1; then
      if setsebool -P antivirus_can_scan_system 1 2>/dev/null; then
        ok "SELinux: boolean antivirus_can_scan_system enabled (persistent)."
      else
        warn "Could not set the SELinux boolean antivirus_can_scan_system: if system path scans fail, set it by hand."
      fi
    fi
  fi
  warn "clamd will run as ROOT and read any file: make sure port $PORT is restricted (use --console-ip)."
  ok "Whole-system scanning configured (User=root${INIT_SYS:+, SELinux handled where present})."
fi

# --on-access: realtime protection. clamonacc uses fanotify to intercept files
# as they are written/opened and has clamd check them.
CLAMONACC_MODE=""
# Whether the realtime scanner is actually running, so the closing summary
# reports what is true rather than what was requested.
ONACC_ACTIVE=0
# 1 when the kernel actually allows fanotify; probed before installing the unit.
ONACC_SUPPORTED=1
if [[ "$ON_ACCESS" -eq 1 ]]; then
  log "--on-access mode: configuring the realtime scanner (clamonacc)..."

  if [[ "$INIT_SYS" != "systemd" ]]; then
    err "--on-access is only supported on systemd systems (here: $INIT_SYS)."
    exit 1
  fi
  if ! command -v clamonacc >/dev/null 2>&1; then
    err "Binary 'clamonacc' not found. On Debian/Ubuntu it ships in clamav-daemon,"
    err "on Fedora/RHEL in the clamd package. Install it and re-run with --skip-install."
    exit 1
  fi

  # Keep only directories that actually exist: an OnAccessIncludePath pointing at
  # a missing path makes clamd fail to start.
  EXISTING_WATCH=()
  for _p in "${WATCH_PATHS[@]}"; do
    if [[ -d "$_p" ]]; then
      EXISTING_WATCH+=("$_p")
    else
      warn "  $_p does not exist on this machine: skipping it."
    fi
  done
  if [[ ${#EXISTING_WATCH[@]} -eq 0 ]]; then
    err "None of the directories given with --watch-path exist. Nothing to watch."
    exit 1
  fi

  set_conf_multi "OnAccessIncludePath" "$CLAMD_CONF" "${EXISTING_WATCH[@]}"
  # /proc /sys /dev /run are virtual filesystems: scanning them is pointless and
  # can hang the daemon. We also exclude the logs and the reporter's spool, which
  # are written precisely in response to a detection.
  set_conf_multi "OnAccessExcludePath" "$CLAMD_CONF" \
    /proc /sys /dev /run /var/log /var/lib/clamav /var/lib/clamav-console-report

  if [[ "$ON_ACCESS_PREVENT" -eq 1 ]]; then
    set_conf_value "OnAccessPrevention" "yes" "$CLAMD_CONF"
    warn "OnAccessPrevention ENABLED: access to detected files will be BLOCKED."
    warn "A false positive on a system file can break running applications."
  else
    set_conf_value "OnAccessPrevention" "no" "$CLAMD_CONF"
    ok "OnAccessPrevention = no (report only: nothing is blocked)."
  fi
  # ExtraScanning adds create/move events: more coverage but much more load.
  # Writing a file is already covered without it.
  set_conf_value "OnAccessExtraScanning" "no" "$CLAMD_CONF"

  # clamonacc hands clamd the already-open file descriptor (--fdpass): that needs
  # a local UNIX socket. Without fd-pass it falls back to --stream, which sends
  # the bytes over the socket (slower, but the path in the log stays correct).
  LOCAL_SOCKET=$(grep -E '^[[:space:]]*LocalSocket[[:space:]]+' "$CLAMD_CONF" | awk '{print $2}' | tail -1)
  if [[ -n "$LOCAL_SOCKET" ]]; then
    CLAMONACC_MODE="--fdpass"
    ok "LocalSocket presente ($LOCAL_SOCKET): uso --fdpass."
  else
    CLAMONACC_MODE="--stream"
    warn "No LocalSocket in $CLAMD_CONF: using --stream (files are sent to clamd"
    warn "over the socket instead of passing the descriptor). It works, but it is slower."
  fi

  # Scan loop: when clamd opens the file to check it, fanotify fires again.
  # With --fdpass the file is not reopened by path so the problem does not arise;
  # with --stream we exclude clamd's user, unless it is root (excluding root
  # would wipe out coverage on a server).
  CLAMD_USER=$(grep -E '^[[:space:]]*User[[:space:]]+' "$CLAMD_CONF" | awk '{print $2}' | tail -1)
  if [[ -n "$CLAMD_USER" && "$CLAMD_USER" != "root" ]]; then
    set_conf_value "OnAccessExcludeUname" "$CLAMD_USER" "$CLAMD_CONF"
    ok "OnAccessExcludeUname = $CLAMD_USER (avoids the scan loop)."
  elif [[ "$CLAMONACC_MODE" == "--stream" ]]; then
    warn "clamd runs as root and --fdpass is unavailable: the clamd user cannot be"
    warn "excluded without wiping out coverage. Watch the logs: if you see the same"
    warn "files rescanned over and over, enable LocalSocket in $CLAMD_CONF."
  fi

  ok "clamd.conf configured for on-access on: ${EXISTING_WATCH[*]}"
fi

# ---------------------------------------------------------------------------
# 7) Socket unit: alcune distro (es. Ubuntu recenti, tramite
#    clamav-daemon-socket-generator) regenerate the .socket ListenStream
#    AUTOMATICALLY by reading TCPSocket/TCPAddr from clamd.conf, on every
#    "daemon-reload". In that case we must NOT add a drop-in of our own,
#    otherwise the bind on the same port is duplicated and the socket unit
#    fails with "Address already in use" (conflicting with itself). On older
#    distros (e.g. Debian bookworm without the generator) the manual drop-in
#    is required instead, so we add it only as a fallback when the generator
#    has not already done the job.
# ---------------------------------------------------------------------------
if [[ -n "$CLAMD_SOCKET" ]]; then
  # Remove any manual drop-in left behind by a previous run of THIS script, so
  # we start clean before deciding again whether one is needed.
  rm -rf "/etc/systemd/system/${CLAMD_SOCKET}.d" 2>/dev/null || true
  rm -f "/etc/systemd/system/${CLAMD_SERVICE}.d/override.conf" 2>/dev/null || true

  # If a previous run had masked the socket, unmask it.
  systemctl unmask "$CLAMD_SOCKET" 2>/dev/null || true

  systemctl daemon-reload

  if [[ "$BIND_ADDR" == "0.0.0.0" || -z "$BIND_ADDR" ]]; then
    LISTEN_VALUE="$PORT"
  else
    LISTEN_VALUE="${BIND_ADDR}:${PORT}"
  fi

  ALREADY_CONFIGURED=0
  if systemctl cat "$CLAMD_SOCKET" 2>/dev/null | grep -qE "ListenStream=($BIND_ADDR:)?$PORT$|ListenStream=0\.0\.0\.0:$PORT$"; then
    ALREADY_CONFIGURED=1
  fi

  if [[ $ALREADY_CONFIGURED -eq 1 ]]; then
    ok "$CLAMD_SOCKET already listens on port $PORT (generated automatically by this distro from clamd.conf). No manual drop-in needed."
  else
    log "$CLAMD_SOCKET has no TCP listener yet: adding a manual drop-in (fallback)..."
    SOCKET_OVERRIDE_DIR="/etc/systemd/system/${CLAMD_SOCKET}.d"
    mkdir -p "$SOCKET_OVERRIDE_DIR"
    cat > "${SOCKET_OVERRIDE_DIR}/tcp-socket.conf" << EOF
[Socket]
ListenStream=${LISTEN_VALUE}
EOF
    systemctl daemon-reload
    ok "TCP listener added manually to $CLAMD_SOCKET (ListenStream=${LISTEN_VALUE})."
  fi
fi

# ---------------------------------------------------------------------------
# 8) Start/enable the services
# ---------------------------------------------------------------------------
log "Starting clamd..."
if [[ "$INIT_SYS" == "systemd" ]]; then
  systemctl daemon-reload

  # Free any leftover process already bound to the port (e.g. from a previous run
  # where clamd bound directly, bypassing systemd).
  if command -v fuser >/dev/null 2>&1; then
    fuser -k "${PORT}/tcp" 2>/dev/null || true
    sleep 1
  fi

  if [[ -n "$CLAMD_SOCKET" ]]; then
    systemctl enable --now "$CLAMD_SOCKET"
  fi
  systemctl enable --now "$CLAMD_SERVICE"
  [[ -n "$FRESHCLAM_SERVICE" ]] && (systemctl enable --now "$FRESHCLAM_SERVICE" >/dev/null 2>&1 || true)

  sleep 2
  if ! systemctl is-active --quiet "$CLAMD_SERVICE"; then
    err "$CLAMD_SERVICE did not start correctly. Last log lines:"
    journalctl -u "$CLAMD_SERVICE" -n 30 --no-pager
    exit 1
  fi
  ok "$CLAMD_SERVICE is running."
else
  rc-update add clamd default 2>/dev/null || true
  rc-service clamd restart
  rc-update add freshclamd default 2>/dev/null || true
  rc-service freshclamd restart 2>/dev/null || true
  sleep 2
  if ! rc-service clamd status | grep -qi started; then
    err "The clamd service (OpenRC) is not running. Check: rc-service clamd status"
    exit 1
  fi
  ok "clamd (OpenRC) is running."
fi

# ---------------------------------------------------------------------------
# 8b) --on-access: realtime scanner + automatic forwarding to the console
# ---------------------------------------------------------------------------
if [[ "$ON_ACCESS" -eq 1 ]]; then
  ONACC_LOG="/var/log/clamav/clamonacc.log"
  REPORT_CONF="/etc/clamav/console-report.conf"
  REPORT_SCRIPT="/usr/local/bin/clamav-onacc-report.sh"
  CLAMONACC_BIN="$(command -v clamonacc)"

  mkdir -p /var/log/clamav /etc/clamav /var/lib/clamav-console-report

  # The console credentials live in a file readable only by root: they do not end
  # up on the systemd unit's command line, where anyone could see them with
  # "systemctl cat" or "ps".
  log "Writing the console configuration to $REPORT_CONF..."
  # The reporter reads this file with "source", so values must be single-quoted:
  # a password containing $, spaces or backticks would otherwise be interpreted
  # as shell code instead of as a password.
  shell_quote() {
    printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
  }
  umask 077
  {
    echo "# Generated by install-clamd-remote.sh on $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# Credentials used by clamav-onacc-report.sh for POST /api/scan/report."
    echo "DASHBOARD_URL=$(shell_quote "$CONSOLE_URL")"
    if [[ -n "$CONSOLE_KEY" ]]; then
      echo "DASHBOARD_AGENT_KEY=$(shell_quote "$CONSOLE_KEY")"
    else
      echo "DASHBOARD_API_USER=$(shell_quote "$CONSOLE_USER")"
      echo "DASHBOARD_API_PASSWORD=$(shell_quote "$CONSOLE_PASS")"
    fi
  } > "$REPORT_CONF"
  chmod 600 "$REPORT_CONF"
  umask 022
  ok "Credentials saved (mode 600, root only)."

  install -m 700 "$REPORT_SCRIPT_SRC" "$REPORT_SCRIPT"
  ok "Reporter installed at $REPORT_SCRIPT."

  # If the distro already ships its own clamonacc unit, stop it: two instances on
  # stessa directory generano eventi doppi e carico inutile.
  for _u in clamav-clamonacc.service clamonacc.service; do
    if unit_exists "$_u"; then
      systemctl disable --now "$_u" >/dev/null 2>&1 || true
      warn "Disabled the distro unit $_u (replaced by clamav-onacc.service)."
    fi
  done

  # Probe before installing anything: fanotify_init() needs CAP_SYS_ADMIN in the
  # host's user namespace, which an unprivileged LXC/Docker container never has.
  # Installing a unit that can never start just produces an endless restart loop
  # filling the journal with the same error, which is worse than not installing it.
  log "Checking whether on-access scanning is possible on this machine..."
  # Run clamonacc briefly and look at what it says. "timeout" is the obvious way
  # to bound it, but if it were missing the probe would come back empty and we
  # would wrongly conclude that fanotify works - so there is a fallback that
  # backgrounds the process and kills it.
  probe_onacc() {
    local tmpf pid
    tmpf="$(mktemp)"
    if command -v timeout >/dev/null 2>&1; then
      timeout 10 "$CLAMONACC_BIN" --foreground --log=/dev/null >"$tmpf" 2>&1 </dev/null || true
    else
      "$CLAMONACC_BIN" --foreground --log=/dev/null >"$tmpf" 2>&1 </dev/null &
      pid=$!
      sleep 8
      kill "$pid" 2>/dev/null || true
      wait "$pid" 2>/dev/null || true
    fi
    cat "$tmpf"
    rm -f "$tmpf"
  }
  ONACC_PROBE="$(probe_onacc)"
  if printf '%s' "$ONACC_PROBE" | grep -q "fanotify_init failed"; then
    CONTAINER_TYPE="none"
    if command -v systemd-detect-virt >/dev/null 2>&1; then
      CONTAINER_TYPE="$(systemd-detect-virt --container 2>/dev/null || echo none)"
    elif [[ -f /run/systemd/container ]]; then
      CONTAINER_TYPE="$(cat /run/systemd/container 2>/dev/null || echo container)"
    elif [[ -f /.dockerenv ]]; then
      CONTAINER_TYPE="docker"
    fi

    err "On-access scanning is NOT possible on this machine: the kernel refused"
    err "fanotify_init (Operation not permitted)."
    if [[ "$CONTAINER_TYPE" != "none" ]]; then
      warn "Cause: this is a container ($CONTAINER_TYPE). fanotify needs CAP_SYS_ADMIN"
      warn "in the host's user namespace, which an unprivileged LXC/Docker container"
      warn "never has - being root inside the container is not enough."
      warn "Options: run the agent on the host, or use a privileged LXC container"
      warn "(unprivileged=0) that keeps CAP_SYS_ADMIN."
    else
      warn "Cause: the kernel denied fanotify_init. Check that the kernel supports"
      warn "fanotify (>= 3.8) and that no sandboxing is stripping CAP_SYS_ADMIN."
    fi
    warn "Not installing clamav-onacc.service: a unit that can never start would"
    warn "only loop on restart and flood the journal."
    warn "Console-driven scans and scheduled scans are unaffected and work here."
    ONACC_SUPPORTED=0
  else
    ONACC_SUPPORTED=1
    ok "fanotify available: installing the realtime scanner."
  fi

  if [[ "$ONACC_SUPPORTED" -eq 1 ]]; then
  log "Creating the systemd units..."
  cat > /etc/systemd/system/clamav-onacc.service << EOF
[Unit]
Description=ClamAV on-access scanner (realtime) for the ClaimAV console
StartLimitIntervalSec=300
StartLimitBurst=3
Documentation=man:clamonacc(8)
After=${CLAMD_SERVICE}
Requires=${CLAMD_SERVICE}

[Service]
Type=simple
# fanotify requires CAP_SYS_ADMIN: clamonacc must run as root.
User=root
ExecStart=${CLAMONACC_BIN} --foreground ${CLAMONACC_MODE} --log=${ONACC_LOG}
# on-failure + a start limit: if on-access turns out to be impossible anyway,
# systemd gives up after a few attempts instead of restarting forever and
# filling the journal with the same error.
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

  cat > /etc/systemd/system/clamav-console-report.service << EOF
[Unit]
Description=Forwards ClamAV on-access detections to the ClaimAV console
After=clamav-onacc.service network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=${REPORT_SCRIPT} --follow ${ONACC_LOG}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  # "|| true": if a service fails to start we want to reach the diagnostic block
  # below and show the journal, not die because of set -e.
  systemctl enable --now clamav-onacc.service || true
  systemctl enable --now clamav-console-report.service || true
  sleep 3

  if [[ "$ONACC_SUPPORTED" -eq 1 ]] && systemctl is-active --quiet clamav-onacc.service; then
    ONACC_ACTIVE=1
    ok "clamav-onacc.service active (realtime scanning on: ${EXISTING_WATCH[*]})."
  elif [[ "$ONACC_SUPPORTED" -eq 0 ]]; then
    ONACC_ACTIVE=0
  else
    ONACC_ACTIVE=0
    err "clamav-onacc.service did not start. Log:"
    journalctl -u clamav-onacc.service -n 30 --no-pager || true

    # fanotify_init() needs CAP_SYS_ADMIN in the INITIAL user namespace. A
    # container does not have it, no matter that the process runs as root, so
    # on-access simply cannot work there: say so plainly instead of leaving the
    # user to guess at a generic "check your kernel".
    CONTAINER_TYPE="none"
    command -v systemd-detect-virt >/dev/null 2>&1 && \
      CONTAINER_TYPE="$(systemd-detect-virt --container 2>/dev/null || echo none)"
    if journalctl -u clamav-onacc.service -n 30 --no-pager 2>/dev/null | grep -q "fanotify_init failed"; then
      if [[ "$CONTAINER_TYPE" != "none" ]]; then
        warn "Cause: this machine is a container ($CONTAINER_TYPE), and fanotify needs"
        warn "CAP_SYS_ADMIN in the host's user namespace. An unprivileged LXC/Docker"
        warn "container never has it, so ClamAV on-access cannot run here."
        warn "Options: run the agent on the host instead, or use a privileged LXC"
        warn "container (unprivileged=0) that keeps CAP_SYS_ADMIN."
      else
        warn "Cause: fanotify_init was denied. Check that the service runs as root"
        warn "and that no sandboxing (SELinux/AppArmor/systemd) is blocking it."
      fi
    else
      warn "Common causes: a kernel without fanotify, or OnAccessIncludePath on an"
      warn "unsupported filesystem (e.g. NFS)."
    fi
    warn "Everything else keeps working: scheduled scans and scans launched from"
    warn "the console do not depend on on-access."
  fi

  if systemctl is-active --quiet clamav-console-report.service; then
    ok "clamav-console-report.service active (following $ONACC_LOG)."
  else
    err "clamav-console-report.service did not start. Log:"
    journalctl -u clamav-console-report.service -n 30 --no-pager || true
  fi
  else
    # on-access impossible here: the log follower would watch a file nothing ever
    # writes, so it is not installed either. The reporter script itself is still
    # installed above, because "--test" is the diagnostic tool.
    log "Skipping clamav-onacc.service and clamav-console-report.service."
  fi

  log "Checking that the console accepts reports from this machine..."
  if "$REPORT_SCRIPT" --test; then
    ok "Console connection verified."
  else
    warn "The test against ${CONSOLE_URL} failed (details above)."
    warn "Realtime detections will be spooled locally until the console is reachable."
    warn "Re-run the check at any time with: sudo $REPORT_SCRIPT --test"
  fi
fi

# ---------------------------------------------------------------------------
# 9) Firewall (best-effort, only when ufw or firewalld is detected)
# ---------------------------------------------------------------------------
if [[ -n "$CONSOLE_IP" ]]; then
  if command -v ufw >/dev/null 2>&1; then
    log "Opening port $PORT on ufw, only for $CONSOLE_IP..."
    ufw allow from "$CONSOLE_IP" to any port "$PORT" proto tcp
    ok "ufw rule added."
  elif command -v firewall-cmd >/dev/null 2>&1; then
    log "Opening port $PORT on firewalld, only for $CONSOLE_IP..."
    firewall-cmd --permanent --add-rich-rule="rule family='ipv4' source address='${CONSOLE_IP}/32' port protocol='tcp' port='${PORT}' accept"
    firewall-cmd --reload
    ok "firewalld rule added."
  else
    warn "No managed firewall (ufw/firewalld) detected: if you use another one (iptables/nftables), open port $PORT manually for $CONSOLE_IP."
  fi
else
  if [[ "$AGENT_MODE" -eq 1 ]]; then
    log "No firewall rule added: with an agent this machine calls the console, so"
    log "nothing needs to be reachable from outside."
  else
    warn "No --console-ip given: no firewall was touched. If one is active, open port $PORT manually for the console's IP."
  fi
fi

# ---------------------------------------------------------------------------
# 10) Verifica finale
# ---------------------------------------------------------------------------
log "Checking that port $PORT is listening..."
if command -v ss >/dev/null 2>&1; then
  LISTEN_LINE=$(ss -tulpn 2>/dev/null | grep ":$PORT " || true)
else
  LISTEN_LINE=$(netstat -tulpn 2>/dev/null | grep ":$PORT " || true)
fi

if [[ -n "$LISTEN_LINE" ]]; then
  ok "clamd is listening on port $PORT:"
  echo "    $LISTEN_LINE"
else
  err "Port $PORT is not listening."
  if [[ "$INIT_SYS" == "systemd" ]]; then
    echo "    sudo systemctl status $CLAMD_SERVICE"
    echo "    sudo journalctl -u $CLAMD_SERVICE -n 50"
  else
    echo "    rc-service clamd status"
  fi
  exit 1
fi

log "PING test against the local daemon..."
if command -v nc >/dev/null 2>&1; then
  PING_RESPONSE=$(echo -e "PING" | nc -q1 127.0.0.1 "$PORT" 2>/dev/null || true)
  if [[ "$PING_RESPONSE" == *"PONG"* ]]; then
    ok "clamd responds correctly (PONG received)."
  else
    warn "No PONG received (reply: '$PING_RESPONSE'). The port is open but the logs are worth a look if the console cannot use it."
  fi
else
  warn "netcat is not installed, skipping the PING test."
fi

echo
if [[ "$AGENT_MODE" -eq 0 ]]; then
  ok "Done. In the web console, add this endpoint under Admin > Endpoints:"
  echo "    Host: $(hostname -I 2>/dev/null | awk '{print $1}') (or the correct IP of this machine)"
  echo "    Port: $PORT"
  echo "    Platform: UNIX"
fi

if [[ "$ON_ACCESS" -eq 1 ]]; then
  echo
  if [[ "$ONACC_ACTIVE" -eq 1 ]]; then
    ok "Realtime protection is ACTIVE. From now on this machine reports detections"
    echo "    on its own: you do not need to launch scans to be alerted."
  else
    # Never claim it is on when the service failed to start: the summary is the
    # one thing people read, and a wrong line here hides a real gap in coverage.
    if [[ "$ONACC_SUPPORTED" -eq 0 ]]; then
      warn "Realtime protection is NOT available on this machine (fanotify denied)."
      echo "    See the explanation above. Console-driven and scheduled scans work normally."
    else
      err "Realtime protection is NOT active: clamav-onacc.service is not running."
      echo "    See the cause above. Scheduled scans and console-launched scans still work."
    fi
  fi
  echo
  echo "    Watched directories:   ${EXISTING_WATCH[*]}"
  echo "    Mode:                  ${CLAMONACC_MODE}, prevention=$([[ $ON_ACCESS_PREVENT -eq 1 ]] && echo BLOCK || echo 'report only')"
  echo "    Scanner log:           $ONACC_LOG"
  echo
  echo "    Service status:"
  echo "      systemctl status clamav-onacc clamav-console-report"
  echo "      journalctl -u clamav-console-report -f"
  if [[ "$ONACC_ACTIVE" -eq 1 ]]; then
    echo
    echo "    End-to-end check (download the EICAR test file into a watched directory):"
    echo "      curl -sO --output-dir ${EXISTING_WATCH[0]} https://secure.eicar.org/eicar.com"
    echo "    Within a few seconds you should see a REALTIME job in the console."
  fi
fi
