#!/usr/bin/env bash
#
# ClaimAV agent - installer generated by the console.
#   Endpoint: @@ENDPOINT_NAME@@
#   Console:  @@CONSOLE_URL@@
#
# This file is self-contained: it already carries this endpoint's key and every
# agent script. Download it and run it, nothing else is needed.
#
#   sudo bash install-agent.sh              # asks what to install
#   sudo bash install-agent.sh --all        # installs everything without asking
#
# The key is valid for THIS endpoint only: it can send reports and receive the
# scans requested by the console, nothing else. If it leaks, rotate it in the
# console (Admin > Endpoints > Rotate) and reinstall.
#
set -euo pipefail

CONSOLE_URL="@@CONSOLE_URL@@"
AGENT_KEY="@@AGENT_KEY@@"
ENDPOINT_NAME="@@ENDPOINT_NAME@@"

CONFIG_FILE="/etc/clamav/console-report.conf"

log()  { echo -e "\033[1;34m[*]\033[0m $*"; }
ok()   { echo -e "\033[1;32m[OK]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }
err()  { echo -e "\033[1;31m[ERROR]\033[0m $*" >&2; }

OS="$(uname -s)"

# ---------------------------------------------------------------------------
# What to install
# ---------------------------------------------------------------------------
WANT_REALTIME=""
WANT_CENTRAL=""
WANT_SCHEDULED=""
EXTRA_ARGS=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --all)        WANT_REALTIME=1; WANT_CENTRAL=1; WANT_SCHEDULED=1; shift ;;
    --realtime)   WANT_REALTIME=1; shift ;;
    --central)    WANT_CENTRAL=1; shift ;;
    --scheduled)  WANT_SCHEDULED=1; shift ;;
    --no-realtime)  WANT_REALTIME=0; shift ;;
    --no-central)   WANT_CENTRAL=0; shift ;;
    --no-scheduled) WANT_SCHEDULED=0; shift ;;
    # Print only the leading comment block: "grep '^#'" would also pick up the
    # comments of the scripts embedded further down.
    -h|--help) awk 'NR==1{next} /^#/{sub(/^# ?/,""); print; next} {exit}' "$0"; exit 0 ;;
    # everything else is passed through to install-clamd-remote.sh (e.g. --watch-path)
    *) EXTRA_ARGS+=("$1"); shift ;;
  esac
done

# The root check sits after argument parsing, so "--help" works without sudo,
# and before the menu, so nobody answers three questions only to be told
# afterwards that privileges are required.
if [[ $EUID -ne 0 ]]; then
  err "Run with sudo/root:  sudo bash $0"
  exit 1
fi

# Detected once, used both to set the realtime default and to explain why.
IS_CONTAINER=""
if command -v systemd-detect-virt >/dev/null 2>&1; then
  IS_CONTAINER="$(systemd-detect-virt --container 2>/dev/null || true)"
  [[ "$IS_CONTAINER" == "none" ]] && IS_CONTAINER=""
elif [[ -f /run/systemd/container ]]; then
  IS_CONTAINER="$(cat /run/systemd/container 2>/dev/null || echo container)"
elif [[ -f /.dockerenv ]]; then
  IS_CONTAINER="docker"
fi

ask() {
  # $1 = question, $2 = default (Y/n)
  local answer
  read -rp "$(echo -e "\033[1;36m?\033[0m $1 [$2] ")" answer || answer=""
  answer="${answer:-$2}"
  [[ "$answer" =~ ^[YySs] ]]
}

# If nothing was selected on the command line, ask - but only when there is a
# terminal. With "curl ... | bash" stdin is the pipe, not the keyboard: there we
# install everything, which is the sensible default.
if [[ -z "$WANT_REALTIME$WANT_CENTRAL$WANT_SCHEDULED" ]]; then
  if [[ -t 0 ]]; then
    echo
    echo "  ClaimAV agent - endpoint '${ENDPOINT_NAME}'"
    echo "  Console: ${CONSOLE_URL}"
    echo
    echo "  Choose what to enable on this machine:"
    echo

    if [[ "$OS" == "Linux" ]]; then
      echo "  1) Realtime protection (on-access)"
      echo "     Files are checked as they are written or opened, and every"
      echo "     detection reaches the console and Telegram immediately."
      # In a container fanotify_init is denied outright, so the answer defaults
      # to No: offering Yes would only install a service that cannot start.
      if [[ -n "$IS_CONTAINER" ]]; then
        echo "     NOT possible here: this machine is a container ($IS_CONTAINER), and"
        echo "     fanotify needs CAP_SYS_ADMIN in the host namespace. Verified:"
        echo "     clamonacc exits with \"fanotify_init failed: Operation not permitted\"."
        ask "Enable realtime protection anyway?" "n" && WANT_REALTIME=1 || WANT_REALTIME=0
      else
        ask "Enable realtime protection?" "Y" && WANT_REALTIME=1 || WANT_REALTIME=0
      fi
    else
      warn "Realtime protection is not available on $OS: ClamAV's on-access scanner"
      warn "uses fanotify, which is Linux-only. Skipping this option."
      WANT_REALTIME=0
    fi

    echo
    echo "  2) Console-driven scans"
    echo "     The console's 'Scan' button starts the scan here, locally: no"
    echo "     permission problems and no inbound ports."
    ask "Enable scans launched from the console?" "Y" && WANT_CENTRAL=1 || WANT_CENTRAL=0

    echo
    echo "  3) Scheduled scan"
    echo "     A full scan every night at 02:30, with the result in the console."
    ask "Enable the scheduled scan?" "Y" && WANT_SCHEDULED=1 || WANT_SCHEDULED=0
    echo
  else
    log "No interactive terminal (script running from a pipe): installing everything."
    log "To choose, download the file and run it, or use --realtime/--central/--scheduled."
    WANT_REALTIME=1; WANT_CENTRAL=1; WANT_SCHEDULED=1
  fi
fi

# Normalise anything left unset to 0
WANT_REALTIME="${WANT_REALTIME:-0}"
WANT_CENTRAL="${WANT_CENTRAL:-0}"
WANT_SCHEDULED="${WANT_SCHEDULED:-0}"

if [[ "$OS" != "Linux" && "$WANT_REALTIME" == "1" ]]; then
  warn "Realtime protection is not supported on $OS (fanotify is Linux-only): skipping it."
  WANT_REALTIME=0
fi

if [[ "$WANT_REALTIME$WANT_CENTRAL$WANT_SCHEDULED" == "000" ]]; then
  err "Nothing was selected for installation."
  exit 1
fi

# fanotify_init() needs CAP_SYS_ADMIN in the host's user namespace, which an
# unprivileged container never has. Warn before installing rather than after the
# service has already failed to start.
if [[ "$WANT_REALTIME" == "1" && -n "$IS_CONTAINER" ]]; then
  warn "This machine is a container ($IS_CONTAINER). ClamAV on-access needs"
  warn "CAP_SYS_ADMIN in the host namespace, which unprivileged LXC/Docker"
  warn "containers do not have: realtime protection will not start."
  warn "The installer probes for it and will skip the service rather than leave"
  warn "a unit that restarts forever. Everything else works fine here."
fi

# ---------------------------------------------------------------------------
# Embedded scripts (no downloads: they are already inside this file)
# ---------------------------------------------------------------------------
WORKDIR="$(mktemp -d)"
trap 'rm -rf "$WORKDIR"' EXIT

write_embedded_scripts() {
  cat > "$WORKDIR/install-clamd-remote.sh" <<'__CLAIMAV_EMBED_CLAMD_INSTALLER__'
@@EMBED_CLAMD_INSTALLER@@
__CLAIMAV_EMBED_CLAMD_INSTALLER__

  cat > "$WORKDIR/clamav-onacc-report.sh" <<'__CLAIMAV_EMBED_ONACC_REPORT__'
@@EMBED_ONACC_REPORT@@
__CLAIMAV_EMBED_ONACC_REPORT__

  cat > "$WORKDIR/clamav-agent-poll.sh" <<'__CLAIMAV_EMBED_AGENT_POLL__'
@@EMBED_AGENT_POLL@@
__CLAIMAV_EMBED_AGENT_POLL__

  cat > "$WORKDIR/clamav-scan-report.sh" <<'__CLAIMAV_EMBED_BATCH_SCAN__'
@@EMBED_BATCH_SCAN@@
__CLAIMAV_EMBED_BATCH_SCAN__

  chmod +x "$WORKDIR"/*.sh
}

write_embedded_scripts
ok "Agent scripts extracted (no download needed)."

# ---------------------------------------------------------------------------
# Configuration shared by every component
# ---------------------------------------------------------------------------
shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

write_agent_config() {
  mkdir -p /etc/clamav
  umask 077
  {
    echo "# Generated by the ClaimAV agent installer on $(date '+%Y-%m-%d %H:%M:%S')"
    echo "# Endpoint: ${ENDPOINT_NAME}"
    echo "DASHBOARD_URL=$(shell_quote "$CONSOLE_URL")"
    echo "DASHBOARD_AGENT_KEY=$(shell_quote "$AGENT_KEY")"
    if [[ "$OS" == "Darwin" ]]; then
      echo "SCAN_PATHS_LIST=$(shell_quote "/Users /Applications")"
    fi
  } > "$CONFIG_FILE"
  chmod 600 "$CONFIG_FILE"
  umask 022
  ok "Configuration saved to $CONFIG_FILE (mode 600, root only)."
}

install_poller_service_linux() {
  install -m 700 "$WORKDIR/clamav-agent-poll.sh" /usr/local/bin/clamav-agent-poll.sh
  cat > /etc/systemd/system/clamav-agent-poll.service << EOF
[Unit]
Description=ClaimAV agent: runs the scans requested by the console
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
ExecStart=/usr/local/bin/clamav-agent-poll.sh --loop
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable clamav-agent-poll.service || true
  # restart, not "enable --now": on a machine already enrolled, this script
  # just rewrote /etc/clamav/console-report.conf with a (possibly different)
  # URL/key, but the process already running read the OLD file at its own
  # startup and never looks at it again - "--now" is a no-op start on an
  # already-active unit, so without an explicit restart the new config would
  # sit on disk unused, sometimes for days, until something else happened to
  # bounce the service.
  systemctl restart clamav-agent-poll.service || true
  sleep 2
  if systemctl is-active --quiet clamav-agent-poll.service; then
    ok "Console-driven scans enabled: the console Scan button reaches this machine."
  else
    err "clamav-agent-poll.service did not start. Log:"
    journalctl -u clamav-agent-poll.service -n 20 --no-pager || true
  fi
}

install_scheduled_linux() {
  install -m 700 "$WORKDIR/clamav-scan-report.sh" /usr/local/bin/clamav-scan-report.sh
  cat > /etc/systemd/system/clamav-scheduled-scan.service << 'EOF'
[Unit]
Description=Scheduled ClamAV scan (result sent to the ClaimAV console)

[Service]
Type=oneshot
User=root
ExecStart=/usr/local/bin/clamav-scan-report.sh
EOF
  cat > /etc/systemd/system/clamav-scheduled-scan.timer << 'EOF'
[Unit]
Description=Nightly ClamAV scan

[Timer]
OnCalendar=*-*-* 02:30:00
Persistent=true

[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now clamav-scheduled-scan.timer || true
  ok "Scheduled scan enabled (every night at 02:30)."
}

# ---------------------------------------------------------------------------
# Linux
# ---------------------------------------------------------------------------
install_linux() {
  write_agent_config

  # clamd is used by every component (the poller prefers clamdscan, which is far
  # faster than clamscan because the signatures already sit in the daemon RAM).
  #
  # --bind 127.0.0.1: with an agent it is the machine that calls the console, not
  # the other way round. clamd therefore has no reason to listen on the network:
  # we keep it on localhost, where only clamdscan and clamonacc reach it. No port
  # exposed, no firewall rule to add.
  #
  # --agent-mode: the installer must not close with "add this endpoint with host
  # and port", which is exactly what an agent makes unnecessary.
  local installer_args=(--scan-system --bind 127.0.0.1 --agent-mode)
  if [[ "$WANT_REALTIME" == "1" ]]; then
    installer_args+=(--on-access --console-url "$CONSOLE_URL" --console-key "$AGENT_KEY")
  fi
  log "Installing and configuring clamd (listening on 127.0.0.1 only)..."
  "$WORKDIR/install-clamd-remote.sh" "${installer_args[@]}" "${EXTRA_ARGS[@]+"${EXTRA_ARGS[@]}"}"

  # The installer rewrites the config when --on-access is used: realign it anyway,
  # so the contents are identical in every case.
  write_agent_config

  [[ "$WANT_CENTRAL"   == "1" ]] && install_poller_service_linux
  [[ "$WANT_SCHEDULED" == "1" ]] && install_scheduled_linux
  return 0
}

# ---------------------------------------------------------------------------
# macOS
# ---------------------------------------------------------------------------
install_macos() {
  # Homebrew's own bin directories: "sudo" on macOS does not always inherit
  # the invoking user's PATH (depends on /etc/sudoers secure_path), and this
  # runs under sudo. The scripts installed below export the same thing again
  # for themselves, since they run later, standalone, under launchd - not
  # under this shell at all.
  export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/local/sbin:$PATH"

  if ! command -v clamdscan >/dev/null 2>&1 && ! command -v clamscan >/dev/null 2>&1; then
    if ! command -v brew >/dev/null 2>&1; then
      err "ClamAV is not installed and Homebrew is not available to install it."
      err "Install Homebrew (https://brew.sh), then either run this script again"
      err "or install ClamAV yourself:  brew install clamav"
      exit 1
    fi
    log "ClamAV not found - installing it via Homebrew..."
    # Homebrew refuses to run as root, but this whole script does (see the root
    # check above): run it as whoever invoked sudo, falling back to the current
    # user on the off chance this is somehow already running unprivileged.
    local brew_user="${SUDO_USER:-$(whoami)}"
    if ! sudo -u "$brew_user" brew install clamav; then
      err "brew install clamav failed. Install it manually and re-run this script:"
      err "    brew install clamav"
      exit 1
    fi
    if ! command -v clamdscan >/dev/null 2>&1 && ! command -v clamscan >/dev/null 2>&1; then
      err "ClamAV was installed but clamdscan/clamscan could not be found afterwards."
      err "Open a new terminal (so PATH is refreshed) and re-run this script."
      exit 1
    fi
    ok "ClamAV installed via Homebrew."

    # A fresh Homebrew install ships no signature database, and freshclam
    # refuses to run until the "Example" placeholder line is removed from
    # freshclam.conf - the same bootstrap install.ps1.tpl does for the Windows
    # package. Only done here, right after a fresh install: per the freshclam
    # gotcha elsewhere in this project, never touch a database that already
    # works, since a failed refresh (proxy, or ClamAV's own 429s) deletes the
    # old files before the new ones ever land.
    local brew_prefix clamav_etc freshclam_conf freshclam_sample
    brew_prefix="$(brew --prefix 2>/dev/null || echo /usr/local)"
    clamav_etc="$brew_prefix/etc/clamav"
    freshclam_conf="$clamav_etc/freshclam.conf"
    freshclam_sample="$clamav_etc/freshclam.conf.sample"
    if [[ ! -f "$freshclam_conf" && -f "$freshclam_sample" ]]; then
      grep -v '^Example$' "$freshclam_sample" > "$freshclam_conf"
    fi
    if [[ -f "$freshclam_conf" ]] && command -v freshclam >/dev/null 2>&1; then
      log "Downloading the virus database (freshclam, first run - can take a minute)..."
      freshclam --config-file="$freshclam_conf" || \
        warn "freshclam failed - check network/proxy, then run it manually: freshclam --config-file=\"$freshclam_conf\""
    else
      warn "freshclam.conf could not be prepared - update the virus database manually."
    fi
  fi

  write_agent_config

  # Dedicated copy of bash, used only to run this agent's own scripts under
  # launchd - not a symlink, an actual copy on its own path. TCC's Full Disk
  # Access is granted per executable path, and the LaunchDaemons below run
  # their script as an argument to bash, so TCC sees the requester as
  # /bin/bash: granting FDA there would hand disk access to every OTHER script
  # anything on this machine runs through bash too (cron, Terminal, anything
  # else), not just this agent. Nothing but the two plists below ever invokes
  # this copy, so the admin only has to trust this agent with that access.
  local agent_bash_dir="/usr/local/libexec/claimav"
  local agent_bash="$agent_bash_dir/agent-bash"
  mkdir -p "$agent_bash_dir"
  cp -f "$(command -v bash)" "$agent_bash"
  chmod 755 "$agent_bash"

  if [[ "$WANT_CENTRAL" == "1" ]]; then
    install -m 700 "$WORKDIR/clamav-agent-poll.sh" /usr/local/bin/clamav-agent-poll.sh
    cat > /Library/LaunchDaemons/com.claimav.agent.poll.plist << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.claimav.agent.poll</string>
    <key>ProgramArguments</key>
    <array>
        <string>$agent_bash</string>
        <string>/usr/local/bin/clamav-agent-poll.sh</string>
        <string>--loop</string>
    </array>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><true/>
    <key>StandardErrorPath</key><string>/var/log/clamav-agent.log</string>
    <key>StandardOutPath</key><string>/var/log/clamav-agent.log</string>
</dict>
</plist>
PLIST
    chmod 644 /Library/LaunchDaemons/com.claimav.agent.poll.plist
    launchctl unload /Library/LaunchDaemons/com.claimav.agent.poll.plist 2>/dev/null || true
    launchctl load  /Library/LaunchDaemons/com.claimav.agent.poll.plist
    ok "Console-driven scans enabled: the console Scan button reaches this machine."
  fi

  if [[ "$WANT_SCHEDULED" == "1" ]]; then
    install -m 700 "$WORKDIR/clamav-scan-report.sh" /usr/local/bin/clamav-scan-report.sh
    cat > /Library/LaunchDaemons/com.claimav.agent.scan.plist << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.claimav.agent.scan</string>
    <key>ProgramArguments</key>
    <array>
        <string>$agent_bash</string>
        <string>/usr/local/bin/clamav-scan-report.sh</string>
    </array>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key><integer>2</integer>
        <key>Minute</key><integer>30</integer>
    </dict>
    <key>StandardErrorPath</key><string>/var/log/clamav-agent.log</string>
    <key>StandardOutPath</key><string>/var/log/clamav-agent.log</string>
</dict>
</plist>
PLIST
    chmod 644 /Library/LaunchDaemons/com.claimav.agent.scan.plist
    launchctl unload /Library/LaunchDaemons/com.claimav.agent.scan.plist 2>/dev/null || true
    launchctl load  /Library/LaunchDaemons/com.claimav.agent.scan.plist
    ok "Scheduled scan enabled (every night at 02:30)."
  fi

  if [[ "$WANT_CENTRAL" == "1" || "$WANT_SCHEDULED" == "1" ]]; then
    # Verified behaviour, not a theoretical concern: since Catalina, macOS's TCC
    # blocks access to protected user data (Desktop, Documents, Downloads, Mail,
    # Messages, Photos, most of ~/Library...) regardless of the caller's UID -
    # being root, which this LaunchDaemon runs as, does NOT bypass it. Without
    # an explicit grant, clamscan/clamdscan silently cannot read almost anything
    # under /Users, and the "some files were unreadable" tolerance a broad scan
    # already needs (see run_command in clamav-agent-poll.sh) reports that as a
    # clean OK instead of an error - a full-disk scan finishes in seconds having
    # actually scanned almost nothing, with no visible failure anywhere.
    warn ""
    warn "IMPORTANT - macOS Full Disk Access required:"
    warn "  System Settings > Privacy & Security > Full Disk Access > add $agent_bash"
    warn "(a private copy of bash used only by this agent, not your system /bin/bash -"
    warn "so this grant doesn't give disk access to every other bash script on the machine)."
    warn "Without it, scans of /Users will silently skip most real files and still"
    warn "report clean. After granting it, restart the agent:"
    warn "  sudo launchctl unload /Library/LaunchDaemons/com.claimav.agent.poll.plist"
    warn "  sudo launchctl load /Library/LaunchDaemons/com.claimav.agent.poll.plist"
  fi
  return 0
}

case "$OS" in
  Linux)  install_linux ;;
  Darwin) install_macos ;;
  *)
    err "Operating system not supported by this script: $OS"
    err "For Windows, download install-agent.ps1 from the console."
    exit 1
    ;;
esac

# ---------------------------------------------------------------------------
# Final verification
# ---------------------------------------------------------------------------

# The reporter doubles as the diagnostic tool, so install it whatever was
# selected: "--test" is the one command to re-run when something looks wrong.
install -m 700 "$WORKDIR/clamav-onacc-report.sh" /usr/local/bin/clamav-onacc-report.sh

echo
log "Checking that the console accepts reports from this machine..."
CONSOLE_OK=0
if /usr/local/bin/clamav-onacc-report.sh --test; then
  CONSOLE_OK=1
fi

# Report what is actually running, not what was requested: a summary claiming
# "active" over a service that failed to start hides a real gap in coverage.
service_state() {
  # $1 = systemd unit, $2 = launchd label
  if [[ "$OS" == "Linux" ]]; then
    systemctl is-active --quiet "$1" 2>/dev/null && echo "active" || echo "NOT running"
  else
    launchctl list 2>/dev/null | grep -q "$2" && echo "loaded" || echo "NOT loaded"
  fi
}

if [[ "$WANT_REALTIME" == "1" ]]; then
  REALTIME_STATE="$(service_state clamav-onacc.service -)"
else
  REALTIME_STATE="not installed"
fi
if [[ "$WANT_CENTRAL" == "1" ]]; then
  CENTRAL_STATE="$(service_state clamav-agent-poll.service com.claimav.agent.poll)"
else
  CENTRAL_STATE="not installed"
fi
if [[ "$WANT_SCHEDULED" == "1" ]]; then
  if [[ "$OS" == "Linux" ]]; then
    systemctl is-enabled --quiet clamav-scheduled-scan.timer 2>/dev/null \
      && SCHEDULED_STATE="enabled (02:30)" || SCHEDULED_STATE="NOT enabled"
  else
    SCHEDULED_STATE="$(service_state - com.claimav.agent.scan)"
  fi
else
  SCHEDULED_STATE="not installed"
fi

echo
ok "Agent '${ENDPOINT_NAME}' installed."
echo "    Realtime (on-access):    ${REALTIME_STATE}"
echo "    Console-driven scans:    ${CENTRAL_STATE}"
echo "    Scheduled scan:          ${SCHEDULED_STATE}"
echo "    Console connection:      $([[ "$CONSOLE_OK" == "1" ]] && echo 'OK' || echo 'FAILED (see above)')"
echo "    Configuration:           $CONFIG_FILE"
echo
echo "    This machine calls the console, not the other way round: leave host and"
echo "    port empty on the endpoint. No inbound port needs opening here."

if [[ "$CONSOLE_OK" != "1" ]]; then
  echo
  warn "The agent is installed but cannot reach the console yet. Detections are"
  warn "spooled locally and sent as soon as the connection works."
  warn "Re-run the check with: sudo /usr/local/bin/clamav-onacc-report.sh --test"
fi
