# ClaimAV agent - installation script generated by the console.
#   Endpoint: @@ENDPOINT_NAME@@
#   Console:  @@CONSOLE_URL@@
#
# The key is valid for THIS endpoint only: it can download the agent and send
# reports, nothing else. If it leaks, rotate it in the console
# (Admin > Endpoints > Rotate) e reinstalla.
#
# USAGE (PowerShell as Administrator):
#   .\install-agent.ps1                        # ti chiede cosa installare
#   .\install-agent.ps1 -All                   # installa tutto senza chiedere (default 02:30)
#   .\install-agent.ps1 -All -ScanTime 03:15   # come sopra, con orario dello scan programmato
#
# NOTE: ClamAV has no realtime protection on Windows (on-access uses fanotify,
# which is Linux-only). What gets installed here is a scheduled scan plus the
# agent that runs scans requested by the console.
#
# If ClamAV itself is missing, this script installs it: winget (Cisco.ClamAV)
# first, falling back to a direct download of the latest GitHub release MSI
# when winget is unavailable or fails. No version is hardcoded either way, so
# the install path does not go stale the way a fixed download URL would.

param(
    # Install everything without asking (also used when the script arrives from
    # a pipe, where there is no terminal to read answers from).
    [switch]$All,
    [switch]$Central,
    [switch]$Scheduled,
    # 24h HH:mm. Used as-is for -All/-Scheduled/non-interactive; the interactive
    # prompt below offers it as the default and lets the user override it.
    [string]$ScanTime = '02:30'
)

function Get-ParsedScanTime {
    param([string]$Value)
    $result = [datetime]::MinValue
    foreach ($fmt in @('HH:mm', 'H:mm', 'h:mm tt', 'hh:mm tt')) {
        if ([datetime]::TryParseExact($Value, $fmt, [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::None, [ref]$result)) {
            return $result
        }
    }
    if ([datetime]::TryParse($Value, [ref]$result)) { return $result }
    return $null
}

$ErrorActionPreference = 'Stop'

$ConsoleUrl   = '@@CONSOLE_URL@@'
$AgentKey     = '@@AGENT_KEY@@'
$EndpointName = '@@ENDPOINT_NAME@@'

$InstallDir = Join-Path $env:ProgramData 'ClaimAV'
$ConfigPath = Join-Path $InstallDir 'agent.conf.json'
$ScanScript = Join-Path $InstallDir 'scan-report.ps1'
$PollScript = Join-Path $InstallDir 'poll-agent.ps1'
$RunCommandScript = Join-Path $InstallDir 'run-command.ps1'
$TaskName   = 'ClaimAV Agent Scan'
$PollTask   = 'ClaimAV Agent Poll'

# Paths scanned by the scheduled task. Change them here if needed.
$ScanPaths = @("$env:SystemDrive\Users", "$env:SystemDrive\ProgramData")

function Write-Info  { param($m) Write-Host "[*] $m"  -ForegroundColor Cyan }
function Write-Ok    { param($m) Write-Host "[OK] $m" -ForegroundColor Green }
function Write-Warn  { param($m) Write-Host "[!] $m"  -ForegroundColor Yellow }
function Write-Err   { param($m) Write-Host "[ERROR] $m" -ForegroundColor Red }

# --- 1) Requires administrator privileges ----------------------------------
$identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Err "Run this script from a PowerShell opened as Administrator."
    exit 1
}

# --- 1b) Cosa installare ----------------------------------------------------
# ClamAV has no realtime protection on Windows (on-access uses fanotify, which
# is Linux-only), so there are two options.
$wantCentral   = $false
$wantScheduled = $false

if ($All) {
    $wantCentral = $true; $wantScheduled = $true
} elseif ($Central -or $Scheduled) {
    $wantCentral = [bool]$Central; $wantScheduled = [bool]$Scheduled
} elseif ([Environment]::UserInteractive -and -not [Console]::IsInputRedirected) {
    Write-Host ''
    Write-Host "  Agent ClaimAV - endpoint '$EndpointName'"
    Write-Host "  Console: $ConsoleUrl"
    Write-Host ''
    Write-Host '  Choose what to enable on this machine:'
    Write-Host ''
    Write-Host '  1) Scansioni centralizzate'
    Write-Host "     The console 'Scan' button starts the scan here, locally."
    $a = Read-Host '  Enable scans launched from the console? [Y/n]'
    $wantCentral = ($a -eq '' -or $a -match '^[SsYy]')
    Write-Host ''
    Write-Host '  2) Scheduled scan'
    Write-Host '     A full scan every night, with the result in the console.'
    $a = Read-Host '  Enable the scheduled scan? [Y/n]'
    $wantScheduled = ($a -eq '' -or $a -match '^[SsYy]')
    if ($wantScheduled) {
        while ($true) {
            $t = Read-Host "     At what time should it run, 24h HH:mm? [$ScanTime]"
            if ($t.Trim() -eq '') { break }
            if (Get-ParsedScanTime $t.Trim()) { $ScanTime = $t.Trim(); break }
            Write-Warn "Invalid time '$t' - use 24h HH:mm, e.g. 02:30."
        }
    }
    Write-Host ''
    Write-Warn 'Note: ClamAV realtime protection is not available on Windows.'
} else {
    Write-Info 'No interactive terminal: installing everything.'
    $wantCentral = $true; $wantScheduled = $true
}

if (-not $wantCentral -and -not $wantScheduled) {
    Write-Err 'Nothing was selected for installation.'
    exit 1
}

$scanTimeParsed = $null
if ($wantScheduled) {
    $scanTimeParsed = Get-ParsedScanTime $ScanTime
    if (-not $scanTimeParsed) {
        Write-Warn "Invalid -ScanTime '$ScanTime', using default 02:30."
        $ScanTime = '02:30'
        $scanTimeParsed = Get-ParsedScanTime $ScanTime
    }
}

# --- 2) Check that ClamAV is present, installing it if necessary -----------
# clamscan.exe, not clamdscan.exe: this agent never installs or configures a
# clamd service/daemon on Windows (no realtime here, see the note above), so
# there is no clamd.conf and nothing listening. clamdscan.exe needs both -
# picking it just because it happens to be present (the official MSI/winget
# package ships both binaries side by side) fails every scan with "ERROR:
# Can't parse clamd configuration file ...\clamd.conf" even though the
# install itself succeeded.
function Find-ClamScan {
    foreach ($candidate in @(
        "$env:ProgramFiles\ClamAV\clamscan.exe",
        "${env:ProgramFiles(x86)}\ClamAV\clamscan.exe"
    )) {
        if (Test-Path $candidate) { return $candidate }
    }
    $cmd = Get-Command clamscan.exe -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($cmd) { return $cmd.Source }
    return $null
}

# "ClamAV 1.4.6/27650/Mon Jan 1 00:00:00 2024" - same format the Linux/macOS
# agents send, so the console shows the signature database version and age
# without needing to connect here. 2>$null (not 2>&1): merging stderr into
# the success stream is what turns a harmless clamscan warning into a
# terminating exception elsewhere in this script; simply discarding it here
# avoids the problem instead of having to reason about it again.
function Get-ClamavVersionString {
    param([string]$ClamScanPath)
    try {
        $v = & $ClamScanPath --version 2>$null | Select-Object -First 1
        if ($v) { return [string]$v }
    } catch { }
    return ''
}

$clamScan = Find-ClamScan

if (-not $clamScan) {
    Write-Warn "ClamAV not found - installing it automatically."
    $installed = $false

    if (Get-Command winget.exe -ErrorAction SilentlyContinue) {
        Write-Info "Installing via winget (Cisco.ClamAV)..."
        # --silent only suppresses the underlying installer's own UI; winget's own
        # progress/resolution output is left to stream to the console instead of
        # being discarded, so a failure here is diagnosable instead of a bare exit
        # code with no context.
        & winget.exe install --id Cisco.ClamAV -e --silent `
            --accept-source-agreements --accept-package-agreements
        if ($LASTEXITCODE -eq 0) {
            $installed = $true
        } else {
            Write-Warn "winget install exited with code $LASTEXITCODE - falling back to a direct download."
        }
    } else {
        Write-Info "winget not available on this machine - falling back to a direct download."
    }

    if (-not $installed) {
        # No fixed version in the URL: ask GitHub for the latest release so this
        # never goes stale the way a hardcoded MSI link would.
        try {
            $arch = switch ($env:PROCESSOR_ARCHITECTURE) {
                'ARM64' { 'arm64' }
                'AMD64' { 'x64' }
                default { 'win32' }
            }
            Write-Info "Looking up the latest ClamAV release for Windows ($arch)..."
            $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/Cisco-Talos/clamav/releases/latest' -TimeoutSec 30
            $asset = $release.assets | Where-Object { $_.name -like "*.win.$arch.msi" } | Select-Object -First 1
            if (-not $asset) { throw "No Windows $arch MSI found in release $($release.tag_name)." }

            $msiPath = Join-Path $env:TEMP $asset.name
            Write-Info "Downloading $($asset.name)..."
            Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $msiPath -TimeoutSec 300

            Write-Info "Installing $($asset.name) (msiexec /quiet)..."
            $msiLog = Join-Path $env:TEMP 'clamav-install.log'
            $p = Start-Process msiexec.exe -ArgumentList "/i `"$msiPath`" /quiet /norestart /l*v `"$msiLog`"" -Wait -PassThru
            Remove-Item $msiPath -ErrorAction SilentlyContinue
            if ($p.ExitCode -ne 0 -and $p.ExitCode -ne 3010) {
                throw "msiexec exited with code $($p.ExitCode) (log: $msiLog)."
            }
            $installed = $true
        } catch {
            Write-Err "Automatic ClamAV install failed: $($_.Exception.Message)"
            Write-Err "Download the Windows package yourself from https://www.clamav.net/downloads ,"
            Write-Err "install it, run 'freshclam' at least once, then re-run this script."
            exit 1
        }
    }

    $clamScan = Find-ClamScan
    if (-not $clamScan) {
        Write-Err "ClamAV was installed but clamscan.exe/clamdscan.exe could not be found afterwards."
        Write-Err "Open a new PowerShell window (so PATH is refreshed) and re-run this script."
        exit 1
    }
    Write-Ok "ClamAV installed: $clamScan"
} else {
    Write-Ok "ClamAV trovato: $clamScan"
}

# --- 2b) Make sure the virus database exists --------------------------------
# A fresh install ships no database, and freshclam refuses to run until the
# "Example" placeholder line is removed from freshclam.conf.
$clamDir  = Split-Path $clamScan -Parent
$dbDir    = Join-Path $clamDir 'database'
$hasMain  = (Test-Path (Join-Path $dbDir 'main.cvd'))  -or (Test-Path (Join-Path $dbDir 'main.cld'))
$hasDaily = (Test-Path (Join-Path $dbDir 'daily.cvd')) -or (Test-Path (Join-Path $dbDir 'daily.cld'))

if (-not ($hasMain -and $hasDaily)) {
    $freshclamExe    = Join-Path $clamDir 'freshclam.exe'
    $freshclamConf   = Join-Path $clamDir 'freshclam.conf'
    # Recent ClamAV Windows packages moved the .sample files out of the install
    # root into a conf_examples subfolder; older ones kept them next to the
    # binaries. Check both so the install root layout does not matter.
    $freshclamSample = @(
        (Join-Path $clamDir 'freshclam.conf.sample'),
        (Join-Path $clamDir 'conf_examples\freshclam.conf.sample')
    ) | Where-Object { Test-Path $_ } | Select-Object -First 1

    if (-not (Test-Path $freshclamConf) -and $freshclamSample) {
        Get-Content $freshclamSample | Where-Object { $_.Trim() -ne 'Example' } |
            Set-Content $freshclamConf -Encoding ASCII
        if (-not (Select-String -Path $freshclamConf -Pattern '^\s*DatabaseDirectory' -Quiet)) {
            Add-Content -Path $freshclamConf -Value "DatabaseDirectory $dbDir"
        }
    } elseif (-not (Test-Path $freshclamConf)) {
        Write-Warn "No freshclam.conf.sample found next to $clamScan or in conf_examples - cannot generate freshclam.conf."
    }

    if ((Test-Path $freshclamExe) -and (Test-Path $freshclamConf)) {
        New-Item -ItemType Directory -Force -Path $dbDir | Out-Null
        Write-Info "Downloading the virus database (freshclam, first run - can take a minute)..."
        # freshclam redraws its progress bar in place with '\r'; captured through
        # a pipe each redraw becomes its own line, which would otherwise flood
        # the console with thousands of near-identical "Time: ..." lines.
        & $freshclamExe --config-file="$freshclamConf" 2>&1 |
            Where-Object { $_ -notmatch '^\s*Time:\s' } |
            ForEach-Object { Write-Host "    $_" }
        if ($LASTEXITCODE -ne 0) {
            Write-Warn "freshclam exited with code $LASTEXITCODE - check network/proxy, then run it manually:"
            Write-Warn "  & `"$freshclamExe`" --config-file=`"$freshclamConf`""
        }
    } elseif (-not (Test-Path $freshclamExe)) {
        Write-Warn "freshclam.exe not found next to $clamScan - update the virus database manually."
    } else {
        Write-Warn "freshclam.conf could not be prepared - update the virus database manually."
    }
}

# --- 3) Configuration (URL + key) ------------------------------------------
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

@{
    ConsoleUrl = $ConsoleUrl
    AgentKey   = $AgentKey
    ScanPaths  = $ScanPaths
    ClamScan   = $clamScan
} | ConvertTo-Json | Set-Content -Path $ConfigPath -Encoding UTF8

# The key is a secret: only SYSTEM and Administrators may read it.
$acl = Get-Acl $ConfigPath
$acl.SetAccessRuleProtection($true, $false)
$acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }
foreach ($who in @('NT AUTHORITY\SYSTEM', 'BUILTIN\Administrators')) {
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        $who, 'FullControl', 'Allow'))) | Out-Null
}
Set-Acl -Path $ConfigPath -AclObject $acl
Write-Ok "Configuration saved to $ConfigPath (readable only by Administrators/SYSTEM)."

# --- 4) Scan script + result reporting -------------------------------------
$scanScriptBody = @'
$ErrorActionPreference = 'Stop'
$cfg  = Get-Content (Join-Path $env:ProgramData 'ClaimAV\agent.conf.json') -Raw | ConvertFrom-Json
$base = $cfg.ConsoleUrl.TrimEnd('/')

$clamavVersion = ''
try { $clamavVersion = [string](& $cfg.ClamScan --version 2>$null | Select-Object -First 1) } catch { }
# Sent on every request, same as clamscan's own version above: there is no
# clamd on Windows (no realtime, see the note at the top of this installer),
# so "unsupported" is a fixed fact about this OS, not something to detect.
$headers = @{ 'X-Agent-Key' = $cfg.AgentKey; 'X-Agent-Clamav' = $clamavVersion; 'X-Agent-OnAccess-Mode' = 'unsupported'; 'X-Agent-OS' = 'windows' }

$findings = New-Object System.Collections.Generic.List[string]
$verdict  = 'OK'
$errorMsg = ''
$remediation     = 'not_attempted'
$remediationPath = ''

# Detection vs Prevention (Admin > Groups > realtime mode). Read-only and
# side-effect-free on purpose: GET /api/agent/commands also CLAIMS any
# pending console-dispatched scan (marks it DISPATCHED, the job RUNNING), and
# this nightly task must not steal a command that belongs to poll-agent.ps1's
# own Scheduled Task - hence the separate /api/agent/mode endpoint.
$mode = $null
try {
    $modeResp = Invoke-RestMethod -Uri "$base/api/agent/mode" -Headers $headers -TimeoutSec 15
    $mode = $modeResp.onAccessMode
} catch { }

$quarantineDir = Join-Path $env:ProgramData 'ClaimAV\quarantine'
# --recursive: unlike clamdscan (which hands directories to clamd, and clamd
# always walks them fully on its own), clamscan.exe does NOT descend into
# subdirectories by default - without this, "scan C:\" only looks at the
# handful of files directly inside C:\ and returns clean in seconds, having
# never touched anything a user or program actually put on disk. An earlier
# fix dropped this flag entirely to silence one build's "unsupported option"
# warning, which killed recursion along with the warning; the warning itself
# is now harmless on its own (see the ErrorActionPreference note below), so
# it can go back in.
$scanArgs = @('--infected', '--recursive')
if ($mode -eq 'prevent') {
    New-Item -ItemType Directory -Force -Path $quarantineDir | Out-Null
    $scanArgs += "--move=$quarantineDir"
}

try {
    # --infected: print detected files only. The output is "<path>: <SIG> FOUND",
    # the very format /api/scan/report already knows how to parse.
    #
    # clamscan writes non-fatal WARNINGs to stderr; with 2>&1 those lines become
    # PowerShell ErrorRecords, and under $ErrorActionPreference = 'Stop' that
    # promotes them to terminating exceptions - a scan that found nothing wrong
    # would still land in the catch block and get reported as ERROR. Relaxing it
    # to 'Continue' for just this call keeps stderr readable without treating it
    # as fatal; $LASTEXITCODE is still the authority on success/failure.
    $ErrorActionPreference = 'Continue'
    $output = & $cfg.ClamScan @scanArgs $cfg.ScanPaths 2>&1
    $exit = $LASTEXITCODE
    $ErrorActionPreference = 'Stop'
    foreach ($line in $output) {
        if ($line -match ' FOUND$') { $findings.Add([string]$line) }
    }
    if ($exit -eq 1) {
        $verdict = 'VIRUS_FOUND'
        if ($mode -eq 'prevent') {
            # clamscan's own --move already did the work; verify against the
            # original path rather than trusting the exit code alone, the same
            # way the other agents confirm what really happened on disk.
            $stillThere = $findings | Where-Object {
                Test-Path -LiteralPath ($_ -replace '^(.*?): .*$', '$1')
            }
            if ($stillThere.Count -eq 0) {
                $remediation     = 'quarantined'
                $remediationPath = $quarantineDir
            } else {
                $remediation = 'failed'
            }
        }
    } elseif ($exit -ne 0) {
        if (($output -join "`n") -match '(?m)^Infected files: 0$') {
            # clamscan exit 2 covers two different situations it cannot tell
            # apart in its own exit code: the scan never really ran, and "it
            # ran to completion, found nothing, but could not open some
            # individual file along the way" (a permission-protected system
            # file, a locked file...). The summary line only appears once a
            # scan has actually finished, so its presence with zero
            # infections means this is the second, harmless case - ordinary
            # noise on a broad target, not worth reporting.
            $verdict = 'OK'
        } else {
            $verdict  = 'ERROR'
            $errorMsg = "clamscan exit $exit`n" + ($output -join "`n")
        }
    }
} catch {
    $verdict  = 'ERROR'
    $errorMsg = $_.Exception.Message
}

# As with the other agents, only what matters is reported: a clean scan must not
# fill up the job list.
if ($verdict -eq 'OK') { exit 0 }

$payload = @{
    hostname        = $env:COMPUTERNAME
    path            = ($cfg.ScanPaths -join ' ')
    verdict         = $verdict
    source          = 'batch'
    findings        = @($findings)
    errorMessage    = $errorMsg
    remediation     = $remediation
    remediationPath = $remediationPath
} | ConvertTo-Json -Depth 4

Invoke-RestMethod -Method Post -Uri "$base/api/scan/report" -Headers $headers `
    -ContentType 'application/json' -Body $payload | Out-Null
'@
Set-Content -Path $ScanScript -Value $scanScriptBody -Encoding UTF8
Write-Ok "Scan script installed at $ScanScript"

# --- 5) Task programmato ----------------------------------------------------
$principalTask = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -DontStopOnIdleEnd

if ($wantScheduled) {
    $action  = New-ScheduledTaskAction -Execute 'powershell.exe' `
                  -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$ScanScript`""
    $trigger = New-ScheduledTaskTrigger -Daily -At $scanTimeParsed
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Principal $principalTask -Settings $settings | Out-Null
    Write-Ok "Task programmato '$TaskName' registrato (ogni notte alle $($scanTimeParsed.ToString('HH:mm')))."
}

# --- 5b) Agent: runs the scans requested by the console ---------------------
# This is what makes the console "Scan" button work for this machine: the
# console queues, the agent picks up and runs locally.
#
# The actual clamscan.exe run happens in a DETACHED process (run-command.ps1,
# below), not inline here. A full-disk scan can run far longer than the
# console's AGENT_ALIVE_WINDOW (15 min, see ApiController.java): it is the GET
# below that updates "last seen" on the console, and the Poll task is
# registered with a 5-minute repetition - if the scan blocked this script the
# way it used to, the task's next tick would find the previous instance still
# running and skip (Task Scheduler's default is not to start a second
# instance), so a machine actively scanning would get flagged offline for as
# long as the scan took. Spawning the scan and returning immediately keeps
# this task quick every time, so the heartbeat never stops.
$pollScriptBody = @'
$ErrorActionPreference = 'Stop'
$cfg = Get-Content (Join-Path $env:ProgramData 'ClaimAV\agent.conf.json') -Raw | ConvertFrom-Json
$base = $cfg.ConsoleUrl.TrimEnd('/')

$clamavVersion = ''
try { $clamavVersion = [string](& $cfg.ClamScan --version 2>$null | Select-Object -First 1) } catch { }
# Sent on every request, same as clamscan's own version above: there is no
# clamd on Windows (no realtime, see the note at the top of this installer),
# so "unsupported" is a fixed fact about this OS, not something to detect.
$headers = @{ 'X-Agent-Key' = $cfg.AgentKey; 'X-Agent-Clamav' = $clamavVersion; 'X-Agent-OnAccess-Mode' = 'unsupported'; 'X-Agent-OS' = 'windows' }

try {
    $resp = Invoke-RestMethod -Uri "$base/api/agent/commands" -Headers $headers -TimeoutSec 15
} catch {
    # Console unreachable: not something to report, just retry on the next pass.
    exit 0
}

# Detection vs Prevention (Admin > Groups > realtime mode). $resp already
# carries it (AgentApiController includes it in the same JSON as the
# commands), so no extra round trip is needed here the way the standalone
# nightly scan script needs one. Cast to string: a group-less endpoint omits
# the property entirely, and passing $null through to run-command.ps1's
# -Mode (a [string] parameter) as a literal argument would error.
$mode = [string]$resp.onAccessMode

$runCommandScript = Join-Path $env:ProgramData 'ClaimAV\run-command.ps1'
foreach ($cmd in $resp.commands) {
    # Targets go through a temp file, not a command-line argument: they can
    # contain spaces and there can be several, and a file sidesteps every
    # quoting edge case Start-Process's -ArgumentList has with those. The
    # child script deletes it once read.
    $targetsFile = Join-Path $env:TEMP "claimav-targets-$($cmd.id).txt"
    Set-Content -LiteralPath $targetsFile -Value $cmd.target -Encoding UTF8
    Start-Process -FilePath 'powershell.exe' -WindowStyle Hidden -ArgumentList @(
        '-NoProfile', '-ExecutionPolicy', 'Bypass', '-File', $runCommandScript,
        '-CommandId', $cmd.id, '-TargetsFile', $targetsFile, '-Mode', $mode
    )
}
'@

# --- 5c) The scan itself, one detached process per command ------------------
# Split out of poll-agent.ps1 (see the note above it) so a long scan can run
# to completion without holding up the next heartbeat.
$runCommandScriptBody = @'
param(
    [Parameter(Mandatory)] [int]$CommandId,
    [Parameter(Mandatory)] [string]$TargetsFile,
    [string]$Mode = ''
)
$ErrorActionPreference = 'Stop'
$cfg  = Get-Content (Join-Path $env:ProgramData 'ClaimAV\agent.conf.json') -Raw | ConvertFrom-Json
$base = $cfg.ConsoleUrl.TrimEnd('/')

$requestedTargets = @()
if (Test-Path -LiteralPath $TargetsFile) {
    $requestedTargets = @(Get-Content -LiteralPath $TargetsFile | Where-Object { $_.Trim() -ne '' })
    Remove-Item -LiteralPath $TargetsFile -Force -ErrorAction SilentlyContinue
}

$clamavVersion = ''
try { $clamavVersion = [string](& $cfg.ClamScan --version 2>$null | Select-Object -First 1) } catch { }
$headers = @{ 'X-Agent-Key' = $cfg.AgentKey; 'X-Agent-Clamav' = $clamavVersion; 'X-Agent-OnAccess-Mode' = 'unsupported'; 'X-Agent-OS' = 'windows' }

$verdict  = 'OK'
$errorMsg = ''
$findings = New-Object System.Collections.Generic.List[string]
$remediation     = 'not_attempted'
$remediationPath = ''
$quarantineDir = Join-Path $env:ProgramData 'ClaimAV\quarantine'
if ($Mode -eq 'prevent') { New-Item -ItemType Directory -Force -Path $quarantineDir | Out-Null }

# Drop targets that don't exist on THIS machine: clamscan given several paths
# at once exits non-zero as soon as ANY of them is missing, which would
# otherwise mark a full-disk/custom-target scan as ERROR even though every
# real directory scanned clean (these lists are configured once for a whole
# fleet, so not every machine has every path).
$targets = @($requestedTargets | Where-Object { Test-Path -LiteralPath $_ })

# --recursive: clamscan.exe does not descend into subdirectories on its own -
# without it, a "full disk" scan of a whole directory tree only ever looks at
# the handful of files directly inside each target.
$scanArgs = @('--infected', '--recursive')
if ($Mode -eq 'prevent') { $scanArgs += "--move=$quarantineDir" }

try {
    if ($targets.Count -eq 0) {
        throw "None of the requested paths exist on this machine: $($requestedTargets -join ' ')"
    }
    # stderr must not be promoted to a terminating error, or a clean/warned
    # scan would be reported as ERROR.
    $ErrorActionPreference = 'Continue'
    $output = & $cfg.ClamScan @scanArgs $targets 2>&1
    $exit = $LASTEXITCODE
    $ErrorActionPreference = 'Stop'
    foreach ($line in $output) {
        if ($line -match ' FOUND$') { $findings.Add([string]$line) }
    }
    if ($findings.Count -gt 0) {
        $verdict = 'VIRUS_FOUND'
        if ($Mode -eq 'prevent') {
            $stillThere = $findings | Where-Object {
                Test-Path -LiteralPath ($_ -replace '^(.*?): .*$', '$1')
            }
            if ($stillThere.Count -eq 0) {
                $remediation     = 'quarantined'
                $remediationPath = $quarantineDir
            } else {
                $remediation = 'failed'
            }
        }
    } elseif ($exit -ne 0 -and ($output -join "`n") -notmatch '(?m)^Infected files: 0$') {
        # clamscan exit 2 covers two different situations it cannot tell
        # apart in its own exit code: the scan never really ran, and "it
        # ran to completion, found nothing, but could not open some
        # individual file along the way". The summary line only appears
        # once a scan has actually finished, so its presence with zero
        # infections ($verdict is already 'OK' from the top of this script)
        # means this is the harmless second case, not a real failure.
        $verdict  = 'ERROR'
        $errorMsg = "clamscan exit $exit`n" + ($output -join "`n")
    }
} catch {
    $verdict  = 'ERROR'
    $errorMsg = $_.Exception.Message
}

$reportedTargets = if ($targets.Count -gt 0) { $targets } else { $requestedTargets }
$payload = @{
    hostname        = $env:COMPUTERNAME
    path            = ($reportedTargets -join ' ')
    verdict         = $verdict
    commandId       = $CommandId
    findings        = @($findings)
    errorMessage    = $errorMsg
    remediation     = $remediation
    remediationPath = $remediationPath
} | ConvertTo-Json -Depth 4

try {
    Invoke-RestMethod -Method Post -Uri "$base/api/scan/report" -Headers $headers `
        -ContentType 'application/json' -Body $payload -TimeoutSec 30 | Out-Null
} catch {
    # The console will time the command out: better than leaving this process hung.
}
'@
Set-Content -Path $PollScript -Value $pollScriptBody -Encoding UTF8
Set-Content -Path $RunCommandScript -Value $runCommandScriptBody -Encoding UTF8
Write-Ok "Agent installed at $PollScript"

if ($wantCentral) {
    $pollAction  = New-ScheduledTaskAction -Execute 'powershell.exe' `
                      -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$PollScript`""
    $pollTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
                      -RepetitionInterval (New-TimeSpan -Minutes 5) `
                      -RepetitionDuration (New-TimeSpan -Days 3650)
    Unregister-ScheduledTask -TaskName $PollTask -Confirm:$false -ErrorAction SilentlyContinue
    Register-ScheduledTask -TaskName $PollTask -Action $pollAction -Trigger $pollTrigger `
        -Principal $principalTask -Settings $settings | Out-Null
    Write-Ok "Task '$PollTask' registered (checks the console every 5 minutes)."
}

# --- 6) Console connection check -------------------------------------------
Write-Info "Checking that the console accepts reports from this machine..."
try {
    $testPayload = @{
        hostname     = $env:COMPUTERNAME
        path         = 'installazione agent'
        verdict      = 'ERROR'
        source       = 'batch'
        errorMessage = "Windows agent connectivity test: console and key are working."
    } | ConvertTo-Json
    Invoke-RestMethod -Method Post -Uri ($ConsoleUrl.TrimEnd('/') + '/api/scan/report') `
        -Headers @{
            'X-Agent-Key'          = $AgentKey
            'X-Agent-Clamav'       = (Get-ClamavVersionString $clamScan)
            'X-Agent-OnAccess-Mode' = 'unsupported'
            'X-Agent-OS'           = 'windows'
        } `
        -ContentType 'application/json' -Body $testPayload | Out-Null
    Write-Ok "Console reachable: look for the test job on the Jobs page."
} catch {
    Write-Warn "Test fallito: $($_.Exception.Message)"
    Write-Warn "Check the console URL, the key and network connectivity."
}

Write-Host ''
Write-Ok "Agent '$EndpointName' installed."
Write-Host ("    Console-driven scans: " + $(if ($wantCentral)   { 'enabled (polls every 5 min)' } else { 'not installed' }))
Write-Host ("    Scheduled scan:       " + $(if ($wantScheduled) { "enabled ($($scanTimeParsed.ToString('HH:mm')))" } else { 'not installed' }))
Write-Warn "ClamAV realtime protection is not available on Windows."
