# ClaimAV agent - installation script generated by the console.
#   Endpoint: @@ENDPOINT_NAME@@
#   Console:  @@CONSOLE_URL@@
#
# The key is valid for THIS endpoint only: it can download the agent and send
# reports, nothing else. If it leaks, rotate it in the console
# (Admin > Endpoints > Rotate) e reinstalla.
#
# USAGE (PowerShell as Administrator):
#   .\install-agent.ps1                        # ti chiede cosa installare
#   .\install-agent.ps1 -All                   # installa tutto senza chiedere (default 02:30)
#   .\install-agent.ps1 -All -ScanTime 03:15   # come sopra, con orario dello scan programmato
#
# NOTE: ClamAV has no realtime protection on Windows (on-access uses fanotify,
# which is Linux-only). What gets installed here is a scheduled scan plus the
# agent that runs scans requested by the console.
#
# If ClamAV itself is missing, this script installs it: winget (Cisco.ClamAV)
# first, falling back to a direct download of the latest GitHub release MSI
# when winget is unavailable or fails. No version is hardcoded either way, so
# the install path does not go stale the way a fixed download URL would.

param(
    # Install everything without asking (also used when the script arrives from
    # a pipe, where there is no terminal to read answers from).
    [switch]$All,
    [switch]$Central,
    [switch]$Scheduled,
    # 24h HH:mm. Used as-is for -All/-Scheduled/non-interactive; the interactive
    # prompt below offers it as the default and lets the user override it.
    [string]$ScanTime = '02:30'
)

function Get-ParsedScanTime {
    param([string]$Value)
    $result = [datetime]::MinValue
    foreach ($fmt in @('HH:mm', 'H:mm', 'h:mm tt', 'hh:mm tt')) {
        if ([datetime]::TryParseExact($Value, $fmt, [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::None, [ref]$result)) {
            return $result
        }
    }
    if ([datetime]::TryParse($Value, [ref]$result)) { return $result }
    return $null
}

$ErrorActionPreference = 'Stop'

$ConsoleUrl   = '@@CONSOLE_URL@@'
$AgentKey     = '@@AGENT_KEY@@'
$EndpointName = '@@ENDPOINT_NAME@@'

$InstallDir = Join-Path $env:ProgramData 'ClaimAV'
$ConfigPath = Join-Path $InstallDir 'agent.conf.json'
$ScanScript = Join-Path $InstallDir 'scan-report.ps1'
$PollScript = Join-Path $InstallDir 'poll-agent.ps1'
$TaskName   = 'ClaimAV Agent Scan'
$PollTask   = 'ClaimAV Agent Poll'

# Paths scanned by the scheduled task. Change them here if needed.
$ScanPaths = @("$env:SystemDrive\Users", "$env:SystemDrive\ProgramData")

function Write-Info  { param($m) Write-Host "[*] $m"  -ForegroundColor Cyan }
function Write-Ok    { param($m) Write-Host "[OK] $m" -ForegroundColor Green }
function Write-Warn  { param($m) Write-Host "[!] $m"  -ForegroundColor Yellow }
function Write-Err   { param($m) Write-Host "[ERROR] $m" -ForegroundColor Red }

# --- 1) Requires administrator privileges ----------------------------------
$identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
$principal = New-Object Security.Principal.WindowsPrincipal($identity)
if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Err "Run this script from a PowerShell opened as Administrator."
    exit 1
}

# --- 1b) Cosa installare ----------------------------------------------------
# ClamAV has no realtime protection on Windows (on-access uses fanotify, which
# is Linux-only), so there are two options.
$wantCentral   = $false
$wantScheduled = $false

if ($All) {
    $wantCentral = $true; $wantScheduled = $true
} elseif ($Central -or $Scheduled) {
    $wantCentral = [bool]$Central; $wantScheduled = [bool]$Scheduled
} elseif ([Environment]::UserInteractive -and -not [Console]::IsInputRedirected) {
    Write-Host ''
    Write-Host "  Agent ClaimAV - endpoint '$EndpointName'"
    Write-Host "  Console: $ConsoleUrl"
    Write-Host ''
    Write-Host '  Choose what to enable on this machine:'
    Write-Host ''
    Write-Host '  1) Scansioni centralizzate'
    Write-Host "     The console 'Scan' button starts the scan here, locally."
    $a = Read-Host '  Enable scans launched from the console? [Y/n]'
    $wantCentral = ($a -eq '' -or $a -match '^[SsYy]')
    Write-Host ''
    Write-Host '  2) Scheduled scan'
    Write-Host '     A full scan every night, with the result in the console.'
    $a = Read-Host '  Enable the scheduled scan? [Y/n]'
    $wantScheduled = ($a -eq '' -or $a -match '^[SsYy]')
    if ($wantScheduled) {
        while ($true) {
            $t = Read-Host "     At what time should it run, 24h HH:mm? [$ScanTime]"
            if ($t.Trim() -eq '') { break }
            if (Get-ParsedScanTime $t.Trim()) { $ScanTime = $t.Trim(); break }
            Write-Warn "Invalid time '$t' - use 24h HH:mm, e.g. 02:30."
        }
    }
    Write-Host ''
    Write-Warn 'Note: ClamAV realtime protection is not available on Windows.'
} else {
    Write-Info 'No interactive terminal: installing everything.'
    $wantCentral = $true; $wantScheduled = $true
}

if (-not $wantCentral -and -not $wantScheduled) {
    Write-Err 'Nothing was selected for installation.'
    exit 1
}

$scanTimeParsed = $null
if ($wantScheduled) {
    $scanTimeParsed = Get-ParsedScanTime $ScanTime
    if (-not $scanTimeParsed) {
        Write-Warn "Invalid -ScanTime '$ScanTime', using default 02:30."
        $ScanTime = '02:30'
        $scanTimeParsed = Get-ParsedScanTime $ScanTime
    }
}

# --- 2) Check that ClamAV is present, installing it if necessary -----------
function Find-ClamScan {
    foreach ($candidate in @(
        "$env:ProgramFiles\ClamAV\clamdscan.exe",
        "$env:ProgramFiles\ClamAV\clamscan.exe",
        "${env:ProgramFiles(x86)}\ClamAV\clamdscan.exe",
        "${env:ProgramFiles(x86)}\ClamAV\clamscan.exe"
    )) {
        if (Test-Path $candidate) { return $candidate }
    }
    $cmd = Get-Command clamdscan.exe, clamscan.exe -ErrorAction SilentlyContinue | Select-Object -First 1
    if ($cmd) { return $cmd.Source }
    return $null
}

$clamScan = Find-ClamScan

if (-not $clamScan) {
    Write-Warn "ClamAV not found - installing it automatically."
    $installed = $false

    if (Get-Command winget.exe -ErrorAction SilentlyContinue) {
        Write-Info "Installing via winget (Cisco.ClamAV)..."
        & winget.exe install --id Cisco.ClamAV -e --silent `
            --accept-source-agreements --accept-package-agreements | Out-Null
        if ($LASTEXITCODE -eq 0) {
            $installed = $true
        } else {
            Write-Warn "winget install exited with code $LASTEXITCODE - falling back to a direct download."
        }
    } else {
        Write-Info "winget not available on this machine - falling back to a direct download."
    }

    if (-not $installed) {
        # No fixed version in the URL: ask GitHub for the latest release so this
        # never goes stale the way a hardcoded MSI link would.
        try {
            $arch = switch ($env:PROCESSOR_ARCHITECTURE) {
                'ARM64' { 'arm64' }
                'AMD64' { 'x64' }
                default { 'win32' }
            }
            Write-Info "Looking up the latest ClamAV release for Windows ($arch)..."
            $release = Invoke-RestMethod -Uri 'https://api.github.com/repos/Cisco-Talos/clamav/releases/latest' -TimeoutSec 30
            $asset = $release.assets | Where-Object { $_.name -like "*.win.$arch.msi" } | Select-Object -First 1
            if (-not $asset) { throw "No Windows $arch MSI found in release $($release.tag_name)." }

            $msiPath = Join-Path $env:TEMP $asset.name
            Write-Info "Downloading $($asset.name)..."
            Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $msiPath -TimeoutSec 300

            Write-Info "Installing $($asset.name) (msiexec /quiet)..."
            $msiLog = Join-Path $env:TEMP 'clamav-install.log'
            $p = Start-Process msiexec.exe -ArgumentList "/i `"$msiPath`" /quiet /norestart /l*v `"$msiLog`"" -Wait -PassThru
            Remove-Item $msiPath -ErrorAction SilentlyContinue
            if ($p.ExitCode -ne 0 -and $p.ExitCode -ne 3010) {
                throw "msiexec exited with code $($p.ExitCode) (log: $msiLog)."
            }
            $installed = $true
        } catch {
            Write-Err "Automatic ClamAV install failed: $($_.Exception.Message)"
            Write-Err "Download the Windows package yourself from https://www.clamav.net/downloads ,"
            Write-Err "install it, run 'freshclam' at least once, then re-run this script."
            exit 1
        }
    }

    $clamScan = Find-ClamScan
    if (-not $clamScan) {
        Write-Err "ClamAV was installed but clamscan.exe/clamdscan.exe could not be found afterwards."
        Write-Err "Open a new PowerShell window (so PATH is refreshed) and re-run this script."
        exit 1
    }
    Write-Ok "ClamAV installed: $clamScan"
} else {
    Write-Ok "ClamAV trovato: $clamScan"
}

# --- 2b) Make sure the virus database exists --------------------------------
# A fresh install ships no database, and freshclam refuses to run until the
# "Example" placeholder line is removed from freshclam.conf.
$clamDir  = Split-Path $clamScan -Parent
$dbDir    = Join-Path $clamDir 'database'
$hasMain  = (Test-Path (Join-Path $dbDir 'main.cvd'))  -or (Test-Path (Join-Path $dbDir 'main.cld'))
$hasDaily = (Test-Path (Join-Path $dbDir 'daily.cvd')) -or (Test-Path (Join-Path $dbDir 'daily.cld'))

if (-not ($hasMain -and $hasDaily)) {
    $freshclamExe    = Join-Path $clamDir 'freshclam.exe'
    $freshclamConf   = Join-Path $clamDir 'freshclam.conf'
    $freshclamSample = Join-Path $clamDir 'freshclam.conf.sample'

    if (-not (Test-Path $freshclamConf) -and (Test-Path $freshclamSample)) {
        Get-Content $freshclamSample | Where-Object { $_.Trim() -ne 'Example' } |
            Set-Content $freshclamConf -Encoding ASCII
        if (-not (Select-String -Path $freshclamConf -Pattern '^\s*DatabaseDirectory' -Quiet)) {
            Add-Content -Path $freshclamConf -Value "DatabaseDirectory $dbDir"
        }
    }

    if (Test-Path $freshclamExe) {
        New-Item -ItemType Directory -Force -Path $dbDir | Out-Null
        Write-Info "Downloading the virus database (freshclam, first run - can take a minute)..."
        & $freshclamExe --config-file="$freshclamConf" 2>&1 | ForEach-Object { Write-Host "    $_" }
        if ($LASTEXITCODE -ne 0) {
            Write-Warn "freshclam exited with code $LASTEXITCODE - check network/proxy, then run it manually:"
            Write-Warn "  & `"$freshclamExe`" --config-file=`"$freshclamConf`""
        }
    } else {
        Write-Warn "freshclam.exe not found next to $clamScan - update the virus database manually."
    }
}

# --- 3) Configuration (URL + key) ------------------------------------------
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null

@{
    ConsoleUrl = $ConsoleUrl
    AgentKey   = $AgentKey
    ScanPaths  = $ScanPaths
    ClamScan   = $clamScan
} | ConvertTo-Json | Set-Content -Path $ConfigPath -Encoding UTF8

# The key is a secret: only SYSTEM and Administrators may read it.
$acl = Get-Acl $ConfigPath
$acl.SetAccessRuleProtection($true, $false)
$acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }
foreach ($who in @('NT AUTHORITY\SYSTEM', 'BUILTIN\Administrators')) {
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
        $who, 'FullControl', 'Allow'))) | Out-Null
}
Set-Acl -Path $ConfigPath -AclObject $acl
Write-Ok "Configuration saved to $ConfigPath (readable only by Administrators/SYSTEM)."

# --- 4) Scan script + result reporting -------------------------------------
$scanScriptBody = @'
$ErrorActionPreference = 'Stop'
$cfg = Get-Content (Join-Path $env:ProgramData 'ClaimAV\agent.conf.json') -Raw | ConvertFrom-Json

$findings = New-Object System.Collections.Generic.List[string]
$verdict  = 'OK'
$errorMsg = ''

try {
    # --infected: print detected files only. The output is "<path>: <SIG> FOUND",
    # the very format /api/scan/report already knows how to parse.
    $output = & $cfg.ClamScan --infected $cfg.ScanPaths 2>&1
    $exit = $LASTEXITCODE
    foreach ($line in $output) {
        if ($line -match ' FOUND$') { $findings.Add([string]$line) }
    }
    if ($exit -eq 1) {
        $verdict = 'VIRUS_FOUND'
    } elseif ($exit -ne 0) {
        $verdict  = 'ERROR'
        $errorMsg = "clamscan exit $exit`n" + ($output -join "`n")
    }
} catch {
    $verdict  = 'ERROR'
    $errorMsg = $_.Exception.Message
}

# As with the other agents, only what matters is reported: a clean scan must not
# fill up the job list.
if ($verdict -eq 'OK') { exit 0 }

$payload = @{
    hostname     = $env:COMPUTERNAME
    path         = ($cfg.ScanPaths -join ' ')
    verdict      = $verdict
    source       = 'batch'
    findings     = @($findings)
    errorMessage = $errorMsg
} | ConvertTo-Json -Depth 4

Invoke-RestMethod -Method Post -Uri ($cfg.ConsoleUrl.TrimEnd('/') + '/api/scan/report') `
    -Headers @{ 'X-Agent-Key' = $cfg.AgentKey } `
    -ContentType 'application/json' -Body $payload | Out-Null
'@
Set-Content -Path $ScanScript -Value $scanScriptBody -Encoding UTF8
Write-Ok "Scan script installed at $ScanScript"

# --- 5) Task programmato ----------------------------------------------------
$principalTask = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -StartWhenAvailable -DontStopOnIdleEnd

if ($wantScheduled) {
    $action  = New-ScheduledTaskAction -Execute 'powershell.exe' `
                  -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$ScanScript`""
    $trigger = New-ScheduledTaskTrigger -Daily -At $scanTimeParsed
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
        -Principal $principalTask -Settings $settings | Out-Null
    Write-Ok "Task programmato '$TaskName' registrato (ogni notte alle $($scanTimeParsed.ToString('HH:mm')))."
}

# --- 5b) Agent: runs the scans requested by the console ---------------------
# This is what makes the console "Scan" button work for this machine: the
# console queues, the agent picks up and runs locally.
$pollScriptBody = @'
$ErrorActionPreference = 'Stop'
$cfg = Get-Content (Join-Path $env:ProgramData 'ClaimAV\agent.conf.json') -Raw | ConvertFrom-Json
$base = $cfg.ConsoleUrl.TrimEnd('/')
$headers = @{ 'X-Agent-Key' = $cfg.AgentKey }

try {
    $resp = Invoke-RestMethod -Uri "$base/api/agent/commands" -Headers $headers -TimeoutSec 15
} catch {
    # Console unreachable: not something to report, just retry on the next pass.
    exit 0
}

foreach ($cmd in $resp.commands) {
    $targets = @($cmd.target -split "`n" | Where-Object { $_.Trim() -ne '' })
    $verdict  = 'OK'
    $errorMsg = ''
    $findings = New-Object System.Collections.Generic.List[string]

    try {
        $output = & $cfg.ClamScan --recursive --infected $targets 2>&1
        $exit = $LASTEXITCODE
        foreach ($line in $output) {
            if ($line -match ' FOUND$') { $findings.Add([string]$line) }
        }
        if ($findings.Count -gt 0) {
            $verdict = 'VIRUS_FOUND'
        } elseif ($exit -ne 0) {
            $verdict  = 'ERROR'
            $errorMsg = "clamscan exit $exit`n" + ($output -join "`n")
        }
    } catch {
        $verdict  = 'ERROR'
        $errorMsg = $_.Exception.Message
    }

    $payload = @{
        hostname     = $env:COMPUTERNAME
        path         = ($targets -join ' ')
        verdict      = $verdict
        commandId    = $cmd.id
        findings     = @($findings)
        errorMessage = $errorMsg
    } | ConvertTo-Json -Depth 4

    try {
        Invoke-RestMethod -Method Post -Uri "$base/api/scan/report" -Headers $headers `
            -ContentType 'application/json' -Body $payload -TimeoutSec 30 | Out-Null
    } catch {
        # The console will time the command out: better than blocking the loop.
    }
}
'@
Set-Content -Path $PollScript -Value $pollScriptBody -Encoding UTF8
Write-Ok "Agent installed at $PollScript"

if ($wantCentral) {
    $pollAction  = New-ScheduledTaskAction -Execute 'powershell.exe' `
                      -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$PollScript`""
    $pollTrigger = New-ScheduledTaskTrigger -Once -At (Get-Date) `
                      -RepetitionInterval (New-TimeSpan -Minutes 5) `
                      -RepetitionDuration (New-TimeSpan -Days 3650)
    Unregister-ScheduledTask -TaskName $PollTask -Confirm:$false -ErrorAction SilentlyContinue
    Register-ScheduledTask -TaskName $PollTask -Action $pollAction -Trigger $pollTrigger `
        -Principal $principalTask -Settings $settings | Out-Null
    Write-Ok "Task '$PollTask' registered (checks the console every 5 minutes)."
}

# --- 6) Console connection check -------------------------------------------
Write-Info "Checking that the console accepts reports from this machine..."
try {
    $testPayload = @{
        hostname     = $env:COMPUTERNAME
        path         = 'installazione agent'
        verdict      = 'ERROR'
        source       = 'batch'
        errorMessage = "Windows agent connectivity test: console and key are working."
    } | ConvertTo-Json
    Invoke-RestMethod -Method Post -Uri ($ConsoleUrl.TrimEnd('/') + '/api/scan/report') `
        -Headers @{ 'X-Agent-Key' = $AgentKey } `
        -ContentType 'application/json' -Body $testPayload | Out-Null
    Write-Ok "Console reachable: look for the test job on the Jobs page."
} catch {
    Write-Warn "Test fallito: $($_.Exception.Message)"
    Write-Warn "Check the console URL, the key and network connectivity."
}

Write-Host ''
Write-Ok "Agent '$EndpointName' installed."
Write-Host ("    Console-driven scans: " + $(if ($wantCentral)   { 'enabled (polls every 5 min)' } else { 'not installed' }))
Write-Host ("    Scheduled scan:       " + $(if ($wantScheduled) { "enabled ($($scanTimeParsed.ToString('HH:mm')))" } else { 'not installed' }))
Write-Warn "ClamAV realtime protection is not available on Windows."
